import React, { createContext, useState, useContext, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { callGemini } from '../services/gemini';
import { Colors } from '../theme';

export type LanguageCode = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'kn' | 'or' | 'ml' | 'pa';

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // General / Tabs
    home: 'Home',
    symptoms: 'Symptoms',
    chat: 'Chat',
    reports: 'Reports',
    more: 'More',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    add: 'Add',
    done: 'Done',
    loading: 'Loading...',

    // Home Screen
    welcome: 'Your Intelligent Health Companion',
    subWelcome: 'AI-guided medical insights & diagnostics at your fingertips.',
    checkSymptomsBtn: 'Check Symptoms',
    chatBotBtn: 'Ask HealAI Bot',
    everythingYouNeed: 'Everything You Need',
    comprehensiveTools: 'Comprehensive tools for better health',
    symptomCheckerTitle: 'Symptom Checker',
    symptomCheckerDesc: 'Analyze symptoms and get immediate medical insights.',
    healthChatbotTitle: 'Medical AI Chatbot',
    healthChatbotDesc: 'Consult with Gemini AI about any health concern or upload reports.',
    healthReportsTitle: 'Health Records',
    healthReportsDesc: 'Analyze scans/lab reports and manage health profiles.',
    nearbyHospitalsTitle: 'Find Care',
    nearbyHospitalsDesc: 'Find verified hospitals and pharmacies near you.',
    howItWorks: 'Three Simple Steps',
    step1Title: 'Describe Symptoms',
    step1Desc: 'Tell our AI about your symptoms using natural language.',
    step2Title: 'Get AI Analysis',
    step2Desc: 'Receive instant, personalized health insights.',
    step3Title: 'Take Action',
    step3Desc: 'Connect with healthcare providers near you.',
    dailyInsight: 'Daily Health Insight',
    healthDisclaimer: 'HealAI provides health information for educational purposes only. It is not a substitute for professional medical advice.',

    // Symptom Checker
    symptomCheckerHeader: 'Symptom Checker',
    disclaimerWarning: 'Not a diagnosis. In case of emergency, call 112 immediately.',
    selectBodyPart: 'Select Affected Area',
    selectBodyPartDesc: 'Choose the primary body region to filter symptoms.',
    selectSymptoms: 'Select Symptoms',
    selectSymptomsDesc: 'Choose symptoms or type your own.',
    typeSymptomPlaceholder: 'Type another symptom...',
    severityDuration: 'Severity & Duration',
    selectSeverity: '1. Select Severity Level',
    selectDuration: '2. How long have you had symptoms?',
    medicalHistory: 'Medical History',
    medicalHistoryDesc: 'Add any preexisting conditions to tailor recommendations.',
    existingConditions: 'Existing Conditions',
    currentMedications: 'Current Medications',
    allergies: 'Allergies',
    conditionsPlaceholder: 'e.g. Diabetes, Hypertension',
    medicationsPlaceholder: 'e.g. Insulin',
    allergiesPlaceholder: 'e.g. Penicillin',
    lifestyleFactors: 'Lifestyle Factors',
    exerciseLevel: 'Exercise Level',
    stressLevel: 'Stress Level',
    dietType: 'Diet Type',
    alcoholIntake: 'Alcohol Intake',
    smokingUse: 'Tobacco / Smoking Use',
    additionalContext: 'Additional Context',
    additionalContextDesc: 'Explain any recent changes or onset details.',
    contextPlaceholder: 'e.g. Started after working long screen hours...',
    analyzeBtn: 'Analyze Symptoms',
    analysisResults: 'Analysis Results',
    potentialConditions: 'Potential Conditions',
    lifestyleImpact: 'Lifestyle Impact',
    remediesTitle: 'Ayurvedic & Lifestyle Remedies',
    emergencySigns: '🚨 Emergency Warning Signs (Red Flags)',
    newAnalysisBtn: 'New Analysis',
    geminiRunning: 'Analyzing symptoms via Gemini AI...',

    // Chat Screen
    chatHeader: 'HealAI Assistant',
    chatPlaceholder: 'Ask about your health...',
    thinking: 'HealAI is thinking...',
    clearChat: 'Clear conversation',
    imageUploaded: 'Image uploaded',

    // Reports Screen
    healthProfile: 'Health Profile',
    healthProfileDesc: 'Tap Edit to set up your health profile',
    uploadReportBtn: 'Upload Medical Report',
    uploadReportDesc: 'Upload lab reports, MRI, CT scans or X-rays for AI analysis',
    personalizedDiet: 'Personalized Diet Plan',
    generateDietBtn: 'Generate',
    regenerateDietBtn: 'Regenerate',
    dietPlaceholder: 'Tap Generate to create your AI-powered meal plan',
    dailyAdviceTitle: 'Daily Advice & Remedies',
    dailyAdvicePlaceholder: 'Tap Generate for personalized daily recommendations',
    naturalRemedies: '🌿 Natural Remedies',

    // More Screen
    healthTools: 'Health Tools',
    educationHub: 'Education Hub',
    educationHubDesc: 'Health articles & videos',
    healthcareResources: 'Healthcare Resources',
    healthcareResourcesDesc: 'Find hospitals near you',
    emergencyCall: 'Emergency Call',
    emergencyCallDesc: 'Dial 112 for emergencies',
    ambulanceCall: 'Ambulance',
    ambulanceCallDesc: 'Call ambulance service',
    changeLanguage: 'Language Settings',
    changeLanguageDesc: 'Change application language',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyDesc: 'Your data is safe',
    aboutApp: 'About HealAI',
    aboutAppDesc: 'Version 1.0.0',
  },
  hi: {
    // General / Tabs
    home: 'होम',
    symptoms: 'লক্ষণ',
    chat: 'चैट',
    reports: 'रिपोर्ट',
    more: 'अधिक',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    edit: 'संपादित करें',
    back: 'पीछे',
    next: 'आगे',
    add: 'जोड़ें',
    done: 'समाप्त',
    loading: 'लोड हो रहा है...',

    // Home Screen
    welcome: 'आपका बुद्धिमान स्वास्थ्य साथी',
    subWelcome: 'आपकी उंगलियों पर एआई-निर्देशित चिकित्सा अंतर्दृष्टि और निदान।',
    checkSymptomsBtn: 'लक्षणों की जांच करें',
    chatBotBtn: 'हीलएआई बॉट से पूछें',
    everythingYouNeed: 'वह सब कुछ जिसकी आपको आवश्यकता है',
    comprehensiveTools: 'बेहतर स्वास्थ्य के लिए व्यापक उपकरण',
    symptomCheckerTitle: 'लक्षण चेकर',
    symptomCheckerDesc: 'लक्षणों का विश्लेषण करें और तत्काल चिकित्सा अंतर्दृष्टि प्राप्त करें।',
    healthChatbotTitle: 'मेडिकल एआई चैटबॉट',
    healthChatbotDesc: 'किसी भी स्वास्थ्य चिंता के बारे में जेमिनी एआई से परामर्श लें या रिपोर्ट अपलोड करें।',
    healthReportsTitle: 'स्वास्थ्य रिकॉर्ड',
    healthReportsDesc: 'स्कैन/लैब रिपोर्ट का विश्लेषण करें और स्वास्थ्य प्रोफाइल प्रबंधित करें।',
    nearbyHospitalsTitle: 'देखभाल खोजें',
    nearbyHospitalsDesc: 'अपने आस-पास सत्यापित अस्पतालों और फार्मेसियों को खोजें।',
    howItWorks: 'तीन सरल कदम',
    step1Title: 'लक्षणों का वर्णन करें',
    step1Desc: 'प्राकृतिक भाषा का उपयोग करके हमारे एआई को अपने लक्षणों के बारे में बताएं।',
    step2Title: 'एआई विश्लेषण प्राप्त करें',
    step2Desc: 'तत्काल, व्यक्तिगत स्वास्थ्य अंतर्दृष्टि प्राप्त करें।',
    step3Title: 'कार्रवाई करें',
    step3Desc: 'अपने आस-पास के स्वास्थ्य सेवा प्रदाताओं से जुड़ें।',
    dailyInsight: 'दैनिक स्वास्थ्य अंतर्दृष्टि',
    healthDisclaimer: 'हीलएआई केवल शैक्षिक उद्देश्यों के लिए स्वास्थ्य जानकारी प्रदान करता है। यह पेशेवर चिकित्सा सलाह का विकल्प नहीं है।',

    // Symptom Checker
    symptomCheckerHeader: 'लक्षण चेकर',
    disclaimerWarning: 'यह कोई अंतिम निदान नहीं है। आपातकालीन स्थिति में तुरंत 112 पर कॉल करें।',
    selectBodyPart: 'प्रभावित क्षेत्र चुनें',
    selectBodyPartDesc: 'लक्षणों को फ़िल्टर करने के लिए प्राथमिक शरीर क्षेत्र चुनें।',
    selectSymptoms: 'लक्षण चुनें',
    selectSymptomsDesc: 'लक्षण चुनें या अपना खुद का टाइप करें।',
    typeSymptomPlaceholder: 'कोई अन्य लक्षण टाइप करें...',
    severityDuration: 'तीव्रता और अवधि',
    selectSeverity: '1. तीव्रता का स्तर चुनें',
    selectDuration: '2. आपको कब से लक्षण महसूस हो रहे हैं?',
    medicalHistory: 'चिकित्सा इतिहास',
    medicalHistoryDesc: 'सिफारिशों को बेहतर बनाने के लिए अपनी पहले से मौजूद स्थितियां जोड़ें।',
    existingConditions: 'पहले से मौजूद बीमारियां',
    currentMedications: 'वर्तमान दवाएं',
    allergies: 'एलर्जी',
    conditionsPlaceholder: 'जैसे- मधुमेह, उच्च रक्तचाप',
    medicationsPlaceholder: 'जैसे- इंसुलिन',
    allergiesPlaceholder: 'जैसे- पेनिसिलिन',
    lifestyleFactors: 'जीवनशैली के कारक',
    exerciseLevel: 'व्यायाम का स्तर',
    stressLevel: 'तनाव का स्तर',
    dietType: 'आहार का प्रकार',
    alcoholIntake: 'शराब का सेवन',
    smokingUse: 'तंबाकू / धूम्रपान का उपयोग',
    additionalContext: 'अतिरिक्त विवरण',
    additionalContextDesc: 'हाल के किसी भी बदलाव या शुरुआत के विवरण को स्पष्ट करें।',
    contextPlaceholder: 'जैसे- काम के लंबे घंटों के बाद शुरू हुआ...',
    analyzeBtn: 'लक्षणों का विश्लेषण करें',
    analysisResults: 'विश्लेषण परिणाम',
    potentialConditions: 'संभावित बीमारियां',
    lifestyleImpact: 'जीवनशैली पर प्रभाव',
    remediesTitle: 'आयुर्वेदिक और जीवनशैली उपचार',
    emergencySigns: '🚨 आपातकालीन चेतावनी संकेत (रेड फ्लैग्स)',
    newAnalysisBtn: 'नया विश्लेषण',
    geminiRunning: 'जेमिनी एआई द्वारा लक्षणों का विश्लेषण किया जा रहा है...',

    // Chat Screen
    chatHeader: 'हीलएआई सहायक',
    chatPlaceholder: 'अपने स्वास्थ्य के बारे में पूछें...',
    thinking: 'हीलएआई सोच रहा है...',
    clearChat: 'बातचीत साफ़ करें',
    imageUploaded: 'छवि अपलोड की गई',

    // Reports Screen
    healthProfile: 'स्वास्थ्य प्रोफ़ाइल',
    healthProfileDesc: 'अपनी स्वास्थ्य प्रोफ़ाइल सेट करने के लिए संपादित करें पर टैप करें',
    uploadReportBtn: 'मेडिकल रिपोर्ट अपलोड करें',
    uploadReportDesc: 'एआई विश्लेषण के लिए लैब रिपोर्ट, एमआरआई, सीटी स्कैन या एक्स-रे अपलोड करें',
    personalizedDiet: 'व्यक्तिगत आहार योजना',
    generateDietBtn: 'तैयार करें',
    regenerateDietBtn: 'पुनः तैयार करें',
    dietPlaceholder: 'अपनी एआई-संचालित भोजन योजना बनाने के लिए तैयार करें पर टैप करें',
    dailyAdviceTitle: 'दैनिक सलाह और उपचार',
    dailyAdvicePlaceholder: 'व्यक्तिगत दैनिक अनुशंसाओं के लिए तैयार करें पर टैप करें',
    naturalRemedies: '🌿 प्राकृतिक उपचार',

    // More Screen
    healthTools: 'स्वास्थ्य उपकरण',
    educationHub: 'शिक्षा केंद्र',
    educationHubDesc: 'स्वास्थ्य लेख और वीडियो',
    healthcareResources: 'स्वास्थ्य संसाधन',
    healthcareResourcesDesc: 'अपने आस-पास के अस्पताल खोजें',
    emergencyCall: 'आपातकालीन कॉल',
    emergencyCallDesc: 'आपात स्थिति के लिए 112 डायल करें',
    ambulanceCall: 'एम्बुलेंस',
    ambulanceCallDesc: 'एम्बुलेंस सेवा को कॉल करें',
    changeLanguage: 'भाषा सेटिंग्स',
    changeLanguageDesc: 'एप्लिकेशन की भाषा बदलें',
    privacyPolicy: 'गोपनीयता नीति',
    privacyPolicyDesc: 'आपका डेटा सुरक्षित है',
    aboutApp: 'हीलएआई के बारे में',
    aboutAppDesc: 'संस्करण 1.0.0',
  },
  bn: {
    home: 'হোম',
    symptoms: 'লক্ষণ',
    chat: 'চ্যাট',
    reports: 'রিপোর্ট',
    more: 'আরও',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    edit: 'সম্পাদনা',
    back: 'পিছনে',
    next: 'পরবর্তী',
    add: 'যোগ করুন',
    done: 'সম্পন্ন',
    loading: 'লোড হচ্ছে...',
    welcome: 'আপনার বুদ্ধিমান স্বাস্থ্য সঙ্গী',
    subWelcome: 'আপনার নখদর্পণে এআই-নির্দেশিত চিকিৎসা অন্তর্দৃষ্টি এবং নির্ণয়।',
    checkSymptomsBtn: 'লক্ষণ পরীক্ষা করুন',
    chatBotBtn: 'হিলএআই বটকে জিজ্ঞাসা করুন',
    everythingYouNeed: 'আপনার যা প্রয়োজন',
    comprehensiveTools: 'উন্নত স্বাস্থ্যের জন্য ব্যাপক সরঞ্জাম',
    symptomCheckerTitle: 'লক্ষণ চেকার',
    symptomCheckerDesc: 'লক্ষণগুলি বিশ্লেষণ করুন এবং অবিলম্বে চিকিৎসা অন্তর্দৃষ্টি পান।',
    healthChatbotTitle: 'মেডিকেল এআই চ্যাটবট',
    healthChatbotDesc: 'যেকোনো স্বাস্থ্য উদ্বেগ সম্পর্কে জেমিনি এআই এর সাথে পরামর্শ করুন বা রিপোর্ট আপলোড করুন।',
    healthReportsTitle: 'স্বাস্থ্য রেকর্ড',
    healthReportsDesc: 'স্ক্যান/ল্যাব রিপোর্ট বিশ্লেষণ করুন এবং স্বাস্থ্য প্রোফাইল পরিচালনা করুন।',
    nearbyHospitalsTitle: 'সেবা খুঁজুন',
    nearbyHospitalsDesc: 'আপনার কাছাকাছি যাচাইकृत হাসপাতাল এবং ফার্মেসী খুঁজুন।',
    howItWorks: 'তিনটি সহজ ধাপ',
    step1Title: 'লক্ষণ বর্ণনা করুন',
    step1Desc: 'প্রাকৃতিক ভাষা ব্যবহার করে আমাদের এআইকে আপনার লক্ষণগুলি বলুন।',
    step2Title: 'এআই বিশ্লেষণ পান',
    step2Desc: 'তাত্ক্ষণিক, ব্যক্তিগতকৃত স্বাস্থ্য অন্তর্দৃষ্টি পান।',
    step3Title: 'পদক্ষেপ নিন',
    step3Desc: 'আপনার কাছাকাছি স্বাস্থ্যসেবা প্রদানকারীদের সাথে সংযোগ করুন।',
    dailyInsight: 'দৈনিক স্বাস্থ্য অন্তর্দৃষ্টি',
    healthDisclaimer: 'হিলএআই শুধুমাত্র শিক্ষামূলক উদ্দেশ্যে স্বাস্থ্য তথ্য প্রদান করে। এটি পেশাদার চিকিৎসা পরামর্শের বিকল্প নয়।',
    symptomCheckerHeader: 'লক্ষণ চেকার',
    disclaimerWarning: 'এটি রোগ নির্ণয় নয়। জরুরি পরিস্থিতিতে অবিলম্বে 112 নম্বরে কল করুন।',
    selectBodyPart: 'আক্রান্ত স্থান নির্বাচন করুন',
    selectBodyPartDesc: 'লক্ষণ ফিল্টার করতে শরীরের প্রাথমিক অংশ বেছে নিন।',
    selectSymptoms: 'লক্ষণ নির্বাচন করুন',
    selectSymptomsDesc: 'লক্ষণগুলি চয়ন করুন বা আপনার নিজস্ব টাইপ করুন।',
    typeSymptomPlaceholder: 'অন্য লক্ষণ টাইপ করুন...',
    severityDuration: 'তীব্রতা ও সময়কাল',
    selectSeverity: '১. তীব্রতার স্তর নির্বাচন করুন',
    selectDuration: '২. কতদিন ধরে লক্ষণ দেখা যাচ্ছে?',
    medicalHistory: 'চিকিৎসার ইতিহাস',
    medicalHistoryDesc: 'সুপারিশগুলি কাস্টমাইজ করতে পূর্ববর্তী অসুস্থতা যোগ করুন।',
    existingConditions: 'বিদ্যমান অসুস্থতা',
    currentMedications: 'চলতি ওষুধ',
    allergies: 'অ্যালার্জি',
    conditionsPlaceholder: 'যেমন- ডায়াবেটিস, উচ্চ রক্তচাপ',
    medicationsPlaceholder: 'যেমন- ইনসুলিন',
    allergiesPlaceholder: 'যেমন- পেনিসিলিন',
    lifestyleFactors: 'জীবনযাত্রার কারণসমূহ',
    exerciseLevel: 'ব্যায়ামের স্তর',
    stressLevel: 'মানসিক চাপের স্তর',
    dietType: 'খাবারের ধরন',
    alcoholIntake: 'অ্যালকোহল সেবন',
    smokingUse: 'তামাক / ধূমপান ব্যবহার',
    additionalContext: 'অতিরিক্ত তথ্য',
    additionalContextDesc: 'সাম্প্রতিক কোনো পরিবর্তন বা শুরুর বিবরণ ব্যাখ্যা করুন।',
    contextPlaceholder: 'যেমন- কাজের দীর্ঘ সময় পরে শুরু হয়েছে...',
    analyzeBtn: 'লक्षण বিশ্লেষণ করুন',
    analysisResults: 'বিশ্লেষণ ফলাফল',
    potentialConditions: 'সম্ভাব্য রোগসমূহ',
    lifestyleImpact: 'জীবনযাত্রায় প্রভাব',
    remediesTitle: 'আয়ুর্বেদিক ও জীবনধারা প্রতিকার',
    emergencySigns: '🚨 জরুরী সতর্কতা লক্ষণ (রেড ফ্ল্যাগ)',
    newAnalysisBtn: 'নতুন विश्लेषण',
    geminiRunning: 'জেমিনি এআই দ্বারা লক্ষণ বিশ্লেষণ করা হচ্ছে...',
    chatHeader: 'হিলএআই সহকারী',
    chatPlaceholder: 'আপনার স্বাস্থ্য সম্পর্কে জিজ্ঞাসা করুন...',
    thinking: 'হিলএআই চিন্তা করছে...',
    clearChat: 'কথোপকথন পরিষ্কার করুন',
    imageUploaded: 'ছবি আপলোড করা হয়েছে',
    healthProfile: 'স্বাস্থ্য প্রোফাইল',
    healthProfileDesc: 'আপনার স্বাস্থ্য প্রোফাইল সেট আপ করতে সম্পাদনা আলতো চাপুন',
    uploadReportBtn: 'মেডিকেল রিপোর্ট আপলোড করুন',
    uploadReportDesc: 'এআই বিশ্লেষণের জন্য ল্যাব রিপোর্ট, এমআরআই, সিটি স্ক্যান বা এক্স-রে আপলোড করুন',
    personalizedDiet: 'ব্যক্তিগত খাদ্য পরিকল্পনা',
    generateDietBtn: 'তৈরি করুন',
    regenerateDietBtn: 'পুনরায় তৈরি করুন',
    dietPlaceholder: 'আপনার এআই-চালিত খাবার পরিকল্পনা তৈরি করতে আলতো চাপুন',
    dailyAdviceTitle: 'দৈনিক পরামর্শ ও প্রতিকার',
    dailyAdvicePlaceholder: 'ব্যক্তিগতকৃত দৈনিক সুপারিশের জন্য আলতো চাপুন',
    naturalRemedies: '🌿 প্রাকৃতিক প্রতিকার',
    healthTools: 'স্বাস্থ্য সরঞ্জাম',
    educationHub: 'শিক্ষা কেন্দ্র',
    educationHubDesc: 'স্বাস্থ্য নিবন্ধ এবং ভিডিও',
    healthcareResources: 'স্বাস্থ্যসেবা সম্পদ',
    healthcareResourcesDesc: 'আপনার কাছাকাছি হাসপাতাল খুঁজুন',
    emergencyCall: 'জরুরী কল',
    emergencyCallDesc: 'জরুরী অবস্থার জন্য 112 ডায়াল করুন',
    ambulanceCall: 'অ্যাম্বুলেন্স',
    ambulanceCallDesc: 'অ্যাম্বুলেন্স পরিষেবা কল করুন',
    changeLanguage: 'ভাষা সেটিংস',
    changeLanguageDesc: '앱লিকেশন ভাষা পরিবর্তন করুন',
    privacyPolicy: 'গোপনীয়তা নীতি',
    privacyPolicyDesc: 'আপনার তথ্য নিরাপদ',
    aboutApp: 'হিলএআই সম্পর্কে',
    aboutAppDesc: 'সংস্করণ ১.০.০',
  },
  te: {
    home: 'హోమ్',
    symptoms: 'లక్షణాలు',
    chat: 'చాట్',
    reports: 'రిపోర్టులు',
    more: 'మరిన్ని',
    cancel: 'రద్దు చేయి',
    save: 'సేవ్ చేయి',
    edit: 'ఎడిట్ చేయి',
    back: 'వెనుకకు',
    next: 'తరువాత',
    add: 'జోడించు',
    done: 'పూర్తయింది',
    loading: 'लोड़ అవుతోంది...',
    welcome: 'మీ తెలివైన ఆరోగ్య సహచరుడు',
    subWelcome: 'మీ వేలికొనలపై AI-ఆధారిత వైద్య అంతర్దృష్టులు మరియు విశ్లేషణలు.',
    checkSymptomsBtn: 'లక్షణాలను తనిఖీ చేయండి',
    chatBotBtn: 'HealAI బాట్‌ను అడగండి',
    everythingYouNeed: 'మీకు కావలసినవన్నీ',
    comprehensiveTools: 'మెరుగైన ఆరోగ్యం కోసం సమగ్ర సాధనాలు',
    symptomCheckerTitle: 'లక్షణాల చెకర్',
    symptomCheckerDesc: 'లక్షణాలను విశ్లేషించండి మరియు తక్షణ వైద్య సమాచారాన్ని పొందండి.',
    healthChatbotTitle: 'మెడికల్ AI చాట్‌బాట్',
    healthChatbotDesc: 'ఏదైనా ఆరోగ్య సమస్య గురించి జెమిని AI తో సంప్రదించండి లేదా రిపోర్టులను అప్‌లోడ్ చేయండి.',
    healthReportsTitle: 'ఆరోగ్య రికార్డులు',
    healthReportsDesc: 'స్కాన్/ల్యాబ్ నివేదికలను విశ్లేషించండి మరియు ఆరోగ్య ప్రొఫైల్‌లను నిర్వహించండి.',
    nearbyHospitalsTitle: 'సంరక్షణను కనుగొనండి',
    nearbyHospitalsDesc: 'మీకు సమీపంలో ధృవీకరించబడిన ఆసుపత్రులు మరియు ఫార్మసీలను కనుగొనండి.',
    howItWorks: 'మూడు సాధారణ దశలు',
    step1Title: 'లಕ್ಷಣాలను వివరించండి',
    step1Desc: 'సహజమైన భాషను ఉపయోగించి మా AI కి మీ లక్షణాల గురించి చెప్పండి.',
    step2Title: 'AI విశ్లేషణను పొందండి',
    step2Desc: 'తక్షణ, వ్యక్తిగతీకరించిన ఆరోగ్య అంతర్దృష్టులను పొందండి.',
    step3Title: 'చర్య తీసుకోండి',
    step3Desc: 'మీకు సమీపంలోని ఆరోగ్య సంరక్షణ ప్రదాతలతో కనెక్ట్ అవ్వండి.',
    dailyInsight: 'రోజువారీ ఆరోగ్య అంతర్దృష్టి',
    healthDisclaimer: 'HealAI విద్యా ప్రయోజనాల కోసం మాత్రమే ఆరోగ్య సమాచారాన్ని అందిస్తుంది. ఇది వృత్తిపరమైన వైద్య సలహాకు ప్రత్యామ్నాయం కాదు.',
    symptomCheckerHeader: 'లక్షణాల చెకర్',
    disclaimerWarning: 'ఇది తుది నిర్ధారణ కాదు. అత్యవసర పరిస్థితిలో వెంటనే 112 కు కాల్ చేయండి.',
    selectBodyPart: 'ప్రభావిత ప్రాంతాన్ని ఎంచుకోండి',
    selectBodyPartDesc: 'లక్షణాలను ఫిల్టర్ చేయడానికి ప్రాథమిక శరీర భాగాన్ని ఎంచుకోండి.',
    selectSymptoms: 'లక్షణాలను ఎంచుకోండి',
    selectSymptomsDesc: 'లక్షణాలను ఎంచుకోండి లేదా మీ స్వంతంగా టైప్ చేయండి.',
    typeSymptomPlaceholder: 'మరో లక్షణాన్ని టైప్ చేయండి...',
    severityDuration: 'తీవ్రత & వ్యవధి',
    selectSeverity: '1. తీవ్రత స్థాయిని ఎంచుకోండి',
    selectDuration: '2. మీకు ఎంతకాలంగా లక్షణాలు ఉన్నాయి?',
    medicalHistory: 'వైద్య చరిత్ర',
    medicalHistoryDesc: 'సిఫార్సులను మెరుగుపరచడానికి మీ మునుపటి ఆరోగ్య పరిస్థితులను జోడించండి.',
    existingConditions: 'మునుపటి పరిస్థితులు',
    currentMedications: 'ప్రస్తుత మందులు',
    allergies: 'అలర్జీలు',
    conditionsPlaceholder: 'ఉదా: మధుమేహం, రక్తపోటు',
    medicationsPlaceholder: 'ఉదా: ఇన్సులిన్',
    allergiesPlaceholder: 'ఉదా: పెన్సిలిన్',
    lifestyleFactors: 'జీవనశైలి కారకాలు',
    exerciseLevel: 'వ్యాయామం స్థాయి',
    stressLevel: 'ఒੱత్తిడి స్థాయి',
    dietType: 'ఆహారం రకం',
    alcoholIntake: 'మద్యపానం అలవాటు',
    smokingUse: 'పొగాకు / ధూమపానం ఉపయోగం',
    additionalContext: 'అదనపు సమాచారం',
    additionalContextDesc: 'ఇటీవలి మార్పులు లేదా ప్రారంభ వివరాలను వివరించండి.',
    contextPlaceholder: 'ఉదా: ఎక్కువ సమయం స్క్రీన్ ముందు పనిచేసిన తర్వాత ప్రారంభమైంది...',
    analyzeBtn: 'లక్షణాలను విశ్లేషించండి',
    analysisResults: 'విశ్లేషణ ఫలితాలు',
    potentialConditions: 'సంభావ్య పరిస్థితులు',
    lifestyleImpact: 'జీవనశైలిపై ప్రభావం',
    remediesTitle: 'ఆయుర్వేద & జీవనశైలి నివారణలు',
    emergencySigns: '🚨 అత్యవసర హెచ్చరిక సంకేతాలు (రెడ్ ఫ్లాగ్స్)',
    newAnalysisBtn: 'కొత్త విశ్లేషణ',
    geminiRunning: 'జెమిని AI ద్వారా లక్షణాలు విశ్లేషించబడుతున్నాయి...',
    chatHeader: 'HealAI సహాయకుడు',
    chatPlaceholder: 'మీ ఆరోగ్యం గురించి అడగండి...',
    thinking: 'HealAI ఆలోచిస్తోంది...',
    clearChat: 'సంభాషణను క్లియర్ చేయి',
    imageUploaded: 'చిత్రం అప్‌లోడ్ చేయబడింది',
    healthProfile: 'ఆరోగ్య ప్రొఫైల్',
    healthProfileDesc: 'మీ ఆరోగ్య ప్రొఫైల్‌ను సెటప్ చేయడానికి ఎడిట్ నొక్కండి',
    uploadReportBtn: 'వైద్య నివేదికను అప్‌లోడ్ చేయండి',
    uploadReportDesc: 'AI విశ్లేషణ కోసం ల్యాబ్ నివేదికలు, MRI, CT స్కాన్‌లు లేదా ఎక్స్-రేలను అప్‌లోడ్ చేయండి',
    personalizedDiet: 'వ్యక్తిగతీకరించిన డైట్ ప్లాన్',
    generateDietBtn: 'రూపొందించు',
    regenerateDietBtn: 'మళ్లీ రూపొందించు',
    dietPlaceholder: 'మీ AI-ఆధారిత భోజన ప్రణాళికను రూపొందించడానికి నొక్కండి',
    dailyAdviceTitle: 'రోజువారీ సలహా & నివారణలు',
    dailyAdvicePlaceholder: 'వ్యక్తిగతీకరించిన రోజువారీ సిఫార్సుల కోసం నొక్కండి',
    naturalRemedies: '🌿 సహజ నివారణలు',
    healthTools: 'ఆరోగ్య సాధనాలు',
    educationHub: 'విద్యా కేంద్రం',
    educationHubDesc: 'ఆరోగ్య కథనాలు & వీడియోలు',
    healthcareResources: 'ఆరోగ్య వనరులు',
    healthcareResourcesDesc: 'మీకు సమీపంలోని ఆసుపత్రులను కనుగొనండి',
    emergencyCall: 'అత్యవసర కాల్',
    emergencyCallDesc: 'అत्यవసర పరిస్థితుల కోసం 112 కు కాల్ చేయండి',
    ambulanceCall: 'అంబులెన్స్',
    ambulanceCallDesc: 'అంబులెన్స్ సేవకు కాల్ చేయండి',
    changeLanguage: 'భాష సెట్టింగులు',
    changeLanguageDesc: 'అప్లికేషన్ భాషను మార్చండి',
    privacyPolicy: 'గోపనీయత విధానం',
    privacyPolicyDesc: 'మీ డేటా సురక్షితం',
    aboutApp: 'HealAI గురించి',
    aboutAppDesc: 'వెర్షన్ 1.0.0',
  },
  mr: {
    home: 'होम',
    symptoms: 'लक्षणे',
    chat: 'चॅट',
    reports: 'रिपोर्ट्स',
    more: 'अधिक',
    cancel: 'रद्द करा',
    save: 'जतन करा',
    edit: 'संपादन',
    back: 'मागे',
    next: 'पुढे',
    add: 'जोडा',
    done: 'पूर्ण',
    loading: 'लोड होत आहे...',
    welcome: 'तुमचा बुद्धिमान आरोग्य सोबती',
    subWelcome: 'तुमच्या बोटांवर एआय-मार्गदर्शित वैद्यकीय अंतर्दृष्टी आणि निदान.',
    checkSymptomsBtn: 'लक्षणे तपासा',
    chatBotBtn: 'HealAI बॉटला विचारा',
    everythingYouNeed: 'तुम्हाला आवश्यक असलेले सर्व काही',
    comprehensiveTools: 'चांगल्या आरोग्यासाठी व्यापक साधने',
    symptomCheckerTitle: 'लक्षण तपासक',
    symptomCheckerDesc: 'लक्षणांचे विश्लेषण करा आणि त्वरित वैद्यकीय अंतर्दृष्टी मिळवा.',
    healthChatbotTitle: 'वैद्यकीय एआय चॅटबॉट',
    healthChatbotDesc: 'कोणत्याही आरोग्याच्या चिंतेबद्दल जेमिनी एआयचा सल्ला घ्या किंवा रिपोर्ट अपलोड करा.',
    healthReportsTitle: 'आरोग्य नोंदी',
    healthReportsDesc: 'स्कॅन/लॅब रिपोर्टचे विश्लेषण करा आणि आरोग्य प्रोफाइल व्यवस्थापित करा.',
    nearbyHospitalsTitle: 'काळजी शोधा',
    nearbyHospitalsDesc: 'तुमच्या जवळील सत्यापित रुग्णालये आणि औषधालये शोधा.',
    howItWorks: 'तीन सोप्या पायऱ्या',
    step1Title: 'लक्षणे सांगा',
    step1Desc: 'नैसर्गिक भाषेचा वापर करून आमच्या एआयला तुमच्या लक्षणांबद्दल सांगा.',
    step2Title: 'एआय विश्लेषण मिळवा',
    step2Desc: 'झटपट, वैयक्तिकृत आरोग्य अंतर्दृष्टी मिळवा.',
    step3Title: 'कृती करा',
    step3Desc: 'तुमच्या जवळील आरोग्य सेवा प्रदात्यांशी संपर्क साधा.',
    dailyInsight: 'दैनिक आरोग्य अंतर्दृष्टी',
    healthDisclaimer: 'HealAI केवळ शैक्षणिक उद्देशाने आरोग्य माहिती प्रदान करते. हे व्यावसायिक वैद्यकीय सल्ल्याला पर्याय नाही.',
    symptomCheckerHeader: 'लक्षण तपासक',
    disclaimerWarning: 'हे अंतिम निदान नाही. आपत्कालीन परिस्थितीत त्वरित 112 वर कॉल करा.',
    selectBodyPart: 'प्रभावित क्षेत्र निवडा',
    selectBodyPartDesc: 'लक्षणे फिल्टर करण्यासाठी शरीराचा प्राथमिक भाग निवडा.',
    selectSymptoms: 'लक्षणे निवडा',
    selectSymptomsDesc: 'लक्षणे निवडा किंवा तुमचे स्वतःचे टाईप करा.',
    typeSymptomPlaceholder: 'इतर लक्षण टाईप करा...',
    severityDuration: 'तीव्रता आणि कालावधी',
    selectSeverity: '१. तीव्रतेची पातळी निवडा',
    selectDuration: '२. तुम्हाला किती दिवसांपासून लक्षणे आहेत?',
    medicalHistory: 'वैद्यकीय इतिहास',
    medicalHistoryDesc: 'शिफारसी सानुकूलित करण्यासाठी तुमचे आधीचे आजार जोडा.',
    existingConditions: 'आधीचे आजार',
    currentMedications: 'सध्याची औषधे',
    allergies: 'ॲलर्जी',
    conditionsPlaceholder: 'उदा. मधुमेह, उच्च रक्तदाब',
    medicationsPlaceholder: 'उदा. इन्सुलिन',
    allergiesPlaceholder: 'उदा. पेनिसिलिन',
    lifestyleFactors: 'जीवनशैलीचे घटक',
    exerciseLevel: 'व्यायामाची पातळी',
    stressLevel: 'तणावाची पातळी',
    dietType: 'आहाराचा प्रकार',
    alcoholIntake: 'मद्यपान',
    smokingUse: 'तंबाखू / धूम्रपान वापर',
    additionalContext: 'अतिरिक्त संदर्भ',
    additionalContextDesc: 'अलीकडील बदल किंवा सुरुवातीचा तपशील स्पष्ट करा.',
    contextPlaceholder: 'उदा. स्क्रीनसमोर बराच वेळ काम केल्यावर सुरू झाले...',
    analyzeBtn: 'लक्षणांचे विश्लेषण करा',
    analysisResults: 'विश्लेषण परिणाम',
    potentialConditions: 'संभावित आजार',
    lifestyleImpact: 'जीवनशैलीवर परिणाम',
    remediesTitle: 'आयुर्वेदिक आणि जीवनशैली उपचार',
    emergencySigns: '🚨 आपत्कालीन चेतावणी चिन्हे (रेड फ्लॅग्स)',
    newAnalysisBtn: 'नवीन विश्लेषण',
    geminiRunning: 'जेमिनी एआय द्वारे लक्षणांचे विश्लेषण केले जात आहे...',
    chatHeader: 'HealAI सहाय्यक',
    chatPlaceholder: 'तुमच्या आरोग्याबद्दल विचारा...',
    thinking: 'HealAI विचार करत आहे...',
    clearChat: 'संभाषण साफ करा',
    imageUploaded: 'प्रतिमा अपलोड केली',
    healthProfile: 'आरोग्य प्रोफाइल',
    healthProfileDesc: 'तुमचे आरोग्य प्रोफाइल सेट करण्यासाठी संपादन दाबा',
    uploadReportBtn: 'वैद्यकीय अहवाल अपलोड करा',
    uploadReportDesc: 'एआय विश्लेषणासाठी लॅब अहवाल, एमआरआय, सीटी स्कॅन किंवा एक्स-रे अपलोड करा',
    personalizedDiet: 'वैयक्तिकृत आहार योजना',
    generateDietBtn: 'तयार करा',
    regenerateDietBtn: 'पुन्हा तयार करा',
    dietPlaceholder: 'तुमची एआय-आधारित आहार योजना तयार करण्यासाठी दाबा',
    dailyAdviceTitle: 'दैनिक सल्ला आणि उपचार',
    dailyAdvicePlaceholder: 'वैयक्तिकृत दैनिक शिफारसींसाठी दाबा',
    naturalRemedies: '🌿 नैसर्गिक उपचार',
    healthTools: 'आरोग्य साधने',
    educationHub: 'शिक्षण केंद्र',
    educationHubDesc: 'आरोग्य लेख आणि व्हिडिओ',
    healthcareResources: 'आरोग्य संसाधने',
    healthcareResourcesDesc: 'तुमच्या जवळील रुग्णालये शोधा',
    emergencyCall: 'आपत्कालीन कॉल',
    emergencyCallDesc: 'आपत्कालीन परिस्थितीसाठी 112 वर कॉल करा',
    ambulanceCall: 'रुग्णवाहिका',
    ambulanceCallDesc: 'रुग्णवाहिका सेवेला कॉल करा',
    changeLanguage: 'भाषा सेटिंग्ज',
    changeLanguageDesc: 'अँप्लिकेशनची भाषा बदला',
    privacyPolicy: 'गोपनीयता धोरण',
    privacyPolicyDesc: 'तुमचा डेटा सुरक्षित आहे',
    aboutApp: 'HealAI बद्दल',
    aboutAppDesc: 'आवृत्ती 1.0.0',
  },
  ta: {
    home: 'முகப்பு',
    symptoms: 'அறிகுறிகள்',
    chat: 'அரட்டை',
    reports: 'அறிக்கைகள்',
    more: 'மேலும்',
    cancel: 'ரத்துசெய்',
    save: 'சேமி',
    edit: 'தொகு',
    back: 'பின்செல்',
    next: 'அடுத்து',
    add: 'சேர்',
    done: 'முடிந்தது',
    loading: 'ஏற்றப்படுகிறது...',
    welcome: 'உங்கள் அறிவார்ந்த சுகாதார துணை',
    subWelcome: 'உங்கள் விரல் நுனியில் AI-வழிநடத்தப்படும் மருத்துவ நுண்ணறிவு மற்றும் பகுப்பாய்வு.',
    checkSymptomsBtn: 'அறிகுறிகளைச் சரிபார்',
    chatBotBtn: 'HealAI பாட்டைக் கேள்',
    everythingYouNeed: 'உங்களுக்குத் தேவையான அனைத்தும்',
    comprehensiveTools: 'சிறந்த ஆரோக்கியத்திற்கான விரிவான கருவிகள்',
    symptomCheckerTitle: 'அறிகுறி சரிபார்ப்பான்',
    symptomCheckerDesc: 'அறிகுறிகளை பகுப்பாய்வு செய்து உடனடியாக மருத்துவ நுண்ணறிவுகளைப் பெறுங்கள்.',
    healthChatbotTitle: 'மருத்துவ AI அரட்டைப் பெட்டி',
    healthChatbotDesc: 'ஏதேனும் சுகாதார கவலை குறித்து ஜெமினி AI உடன் கலந்தாலோசிக்கவும் அல்லது அறிக்கைகளைப் பதிவேற்றவும்.',
    healthReportsTitle: 'சுகாதார பதிவுகள்',
    healthReportsDesc: 'ஸ்கேன்/ஆய்வக அறிக்கைகளைப் பகுப்பாய்வு செய்து சுகாதார சுயவிவரங்களை நிர்வகிக்கவும்.',
    nearbyHospitalsTitle: 'சிகிச்சை நிலையங்கள்',
    nearbyHospitalsDesc: 'உங்களுக்கு அருகிலுள்ள சரிபார்க்கப்பட்ட மருத்துவமனைகள் மற்றும் மருந்தகங்களைக் கண்டறியவும்.',
    howItWorks: 'மூன்று எளிய படிகள்',
    step1Title: 'அறிகுறிகளை விவரி',
    step1Desc: 'இயற்கையான மொழியைப் பயன்படுத்தி எங்கள் AI-யிடம் உங்கள் அறிகுறிகளைக் கூறவும்.',
    step2Title: 'AI பகுப்பாய்வைப் பெறு',
    step2Desc: 'உடனடி, தனிப்பயனாக்கப்பட்ட சுகாதார நுண்ணறிவுகளைப் பெறுங்கள்.',
    step3Title: 'நடவடிக்கை எடு',
    step3Desc: 'உங்களுக்கு அருகிலுள்ள சுகாதார வழங்குநர்களுடன் இணையுங்கள்.',
    dailyInsight: 'தினசரி சுகாதார நுண்ணறிவு',
    healthDisclaimer: 'HealAI கல்வி நோக்கங்களுக்காக மட்டுமே சுகாதார தகவல்களை வழங்குகிறது. இது தொழில்முறை மருத்துவ ஆலோசனைக்கு மாற்றாகாது.',
    symptomCheckerHeader: 'அறிகுறி சரிபார்ப்பான்',
    disclaimerWarning: 'இது இறுதி நோயறிதல் அல்ல. அவசர காலங்களில் உடனடியாக 112 ஐ அழைக்கவும்.',
    selectBodyPart: 'பாதிக்கப்பட்ட பகுதியைத் தேர்ந்தெடு',
    selectBodyPartDesc: 'அறிகுறிகளை வடிகட்ட உடலின் முதன்மைப் பகுதியைத் தேர்ந்தெடுக்கவும்.',
    selectSymptoms: 'அறிகுறிகளைத் தேர்ந்தெடு',
    selectSymptomsDesc: 'அறிகுறிகளைத் தேர்ந்தெடுக்கவும் அல்லது சொந்தமாக தட்டச்சு செய்யவும்.',
    typeSymptomPlaceholder: 'வேறு அறிகுறியைத் தட்டச்சு செய்க...',
    severityDuration: 'தீவிரம் & காலம்',
    selectSeverity: '1. தீவிரத் தன்மையைத் தேர்ந்தெடுக்கவும்',
    selectDuration: '2. எவ்வளவு காலமாக அறிகுறிகள் உள்ளன?',
    medicalHistory: 'மருத்துவ வரலாறு',
    medicalHistoryDesc: 'பரிந்துரைகளை மேம்படுத்த உங்கள் முந்தைய சுகாதார நிலைமைகளைச் சேர்க்கவும்.',
    existingConditions: 'முந்தைய நிலைமைகள்',
    currentMedications: 'தற்போதைய மருந்துகள்',
    allergies: 'ஒவ்வாமை (அலர்ஜி)',
    conditionsPlaceholder: 'உதாரணமாக: நீரிழிவு, உயர் இரத்த அழுத்தம்',
    medicationsPlaceholder: 'உதாரணமாக: இன்சுலின்',
    allergiesPlaceholder: 'உதாரணமாக: பென்சிலின்',
    lifestyleFactors: 'வாழ்க்கை முறை காரணிகள்',
    exerciseLevel: 'உடற்பயிற்சி நிலை',
    stressLevel: 'மன அழுத்த நிலை',
    dietType: 'உணவு வகை',
    alcoholIntake: 'மது அருந்துதல்',
    smokingUse: 'புகையிலை / புகைபிடித்தல் பயன்பாடு',
    additionalContext: 'கூடுதல் தகவல்',
    additionalContextDesc: 'சமீபத்திய மாற்றங்கள் அல்லது ஆரம்ப விவரங்களை விவரிக்கவும்.',
    contextPlaceholder: 'உதாரணமாக: கணினி முன் நீண்ட நேரம் வேலை செய்த பிறகு தொடங்கியது...',
    analyzeBtn: 'அறிகுறிகளை பகுப்பாய்வு செய்',
    analysisResults: 'பகுப்பாய்வு முடிவுகள்',
    potentialConditions: 'சாத்தியமான நோய்கள்',
    lifestyleImpact: 'வாழ்க்கை முறை மீதான தாக்கம்',
    remediesTitle: 'ஆயுர்வேத & வாழ்க்கை முறை தீர்வுகள்',
    emergencySigns: '🚨 அவசர எச்சரிக்கை அறிகுறிகள் (சிவப்பு எச்சரிக்கைகள்)',
    newAnalysisBtn: 'புதிய பகுப்பாய்வு',
    geminiRunning: 'ஜெமினி AI மூலம் அறிகுறிகள் பகுப்பாய்வு செய்யப்படுகின்றன...',
    chatHeader: 'HealAI உதவியாளர்',
    chatPlaceholder: 'உங்கள் ஆரோக்கியத்தைப் பற்றிக் கேளுங்கள்...',
    thinking: 'HealAI யோசிக்கிறது...',
    clearChat: 'உரையாடலை அழி',
    imageUploaded: 'படம் பதிவேற்றப்பட்டது',
    healthProfile: 'சுகாதார சுயவிவரம்',
    healthProfileDesc: 'உங்கள் சுகாதார சுயவிவரத்தை அமைக்க தொகு என்பதைத் தட்டவும்',
    uploadReportBtn: 'மருத்துவ அறிக்கையைப் பதிவேற்று',
    uploadReportDesc: 'AI பகுப்பாய்விற்காக ஆய்வக அறிக்கைகள், எம்ஆர்আই, சிடி ஸ்கேன் அல்லது எக்ஸ்-ரேக்களைப் பதிவேற்றவும்',
    personalizedDiet: 'தனிப்பயனாக்கப்பட்ட உணவுத் திட்டம்',
    generateDietBtn: 'உருவாக்கு',
    regenerateDietBtn: 'மீண்டும் உருவாக்கு',
    dietPlaceholder: 'உங்கள் AI-இயங்கும் உணவுத் திட்டத்தை உருவாக்க தட்டவும்',
    dailyAdviceTitle: 'தினசரி ஆலோசனை & தீர்வுகள்',
    dailyAdvicePlaceholder: 'தனிப்பயனாக்கப்பட்ட தினசரி பரிந்துரைகளுக்கு தட்டவும்',
    naturalRemedies: '🌿 இயற்கை தீர்வுகள்',
    healthTools: 'சுகாதார கருவிகள்',
    educationHub: 'கல்வி மையம்',
    educationHubDesc: 'சுகாதாரக் கட்டுரைகள் & வீடியோக்கள்',
    healthcareResources: 'சுகாதார வளங்கள்',
    healthcareResourcesDesc: 'உங்களுக்கு அருகிலுள்ள மருத்துவமனைகளைக் கண்டறியவும்',
    emergencyCall: 'அவசர அழைப்பு',
    emergencyCallDesc: 'அவசர தேவைகளுக்கு 112 ஐ அழைக்கவும்',
    ambulanceCall: 'ஆம்புலன்ஸ்',
    ambulanceCallDesc: 'ஆம்புலன்ஸ் சேவைக்கு அழைக்கவும்',
    changeLanguage: 'மொழி அமைப்புகள்',
    changeLanguageDesc: 'செயலியின் மொழியை மாற்றவும்',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    privacyPolicyDesc: 'உங்கள் தரவு பாதுகாப்பானது',
    aboutApp: 'HealAI பற்றி',
    aboutAppDesc: 'பதிப்பு 1.0.0',
  },
  gu: {
    home: 'હોમ',
    symptoms: 'લક્ષણો',
    chat: 'ચેટ',
    reports: 'રિપોર્ટ્સ',
    more: 'વધુ',
    cancel: 'રદ કરો',
    save: 'સાચવો',
    edit: 'ફેરફાર કરો',
    back: 'પાછા',
    next: 'આગળ',
    add: 'ઉમેરો',
    done: 'પૂર્ણ',
    loading: 'લોડ થઈ રહ્યું છે...',
    welcome: 'તમારો બુદ્ધિશાળી આરોગ્ય સાથી',
    subWelcome: 'તમારી આંગળીના ટેરવે AI-માર્ગદર્શિત તબીબી આંતરદૃષ્ટિ અને નિદાન.',
    checkSymptomsBtn: 'લક્ષણો તપાસો',
    chatBotBtn: 'HealAI બોટને પૂછો',
    everythingYouNeed: 'તમને જરૂરી બધું જ',
    comprehensiveTools: 'વધુ સારા સ્વાસ્થ્ય માટે વ્યાપક સાધનો',
    symptomCheckerTitle: 'લક્ષણ ચેકર',
    symptomCheckerDesc: 'લક્ષણોનું વિશ્લેષણ કરો અને તાત્કાલિક તબીબી માહિતી મેળવો.',
    healthChatbotTitle: 'મેડિકલ AI ચેટબોટ',
    healthChatbotDesc: 'કોઈપણ સ્વાસ્થ્ય સમસ્યા વિશે જેમિની AI ની સલાહ લો અથવા રિપોર્ટ્સ અપલોડ કરો.',
    healthReportsTitle: 'હેલ્થ રેકોર્ડ્સ',
    healthReportsDesc: 'સ્કેન/લેબ રિપોર્ટ્સનું વિશ્લેષણ કરો અને હેલ્થ પ્રોફાઇલનું સંચાલન કરો.',
    nearbyHospitalsTitle: 'સારવાર શોધો',
    nearbyHospitalsDesc: 'તમારી નજીકની વેરિફાઇડ હોસ્પિટલો અને ફાર્મસીઓ શોધો.',
    howItWorks: 'ત્રણ સરળ પગલાં',
    step1Title: 'લક્ષણોનું વર્ણન કરો',
    step1Desc: 'કુદરતી ભાષાનો ઉપયોગ કરીને અમારા AI ને તમારા લક્ષણો વિશે જણાવો.',
    step2Title: 'AI વિશ્લેષણ મેળવો',
    step2Desc: 'તાત્કાલિક, વ્યક્તિગત કરેલ સ્વાસ્થ્ય આંતરદૃષ્ટિ મેળવો.',
    step3Title: 'પગલાં લો',
    step3Desc: 'તમારી નજીકના આરોગ્ય સેવા પ્રદાતાઓ સાથે જોડાઓ.',
    dailyInsight: 'દૈનિક સ્વાસ્થ્ય આંતરદૃષ્ટિ',
    healthDisclaimer: 'HealAI માત્ર શૈક્ષણિક હેતુઓ માટે જ સ્વાસ્થ્ય માહિતી પ્રદાન કરે છે. તે વ્યાવસાયિક તબીબી સલાહનો વિકલ્પ નથી.',
    symptomCheckerHeader: 'લક્ષણ ચેકર',
    disclaimerWarning: 'આ કોઈ અંતિમ નિદાન નથી. કટોકટીની સ્થિતિમાં તરત જ 112 પર કૉલ કરો.',
    selectBodyPart: 'અસરગ્રસ્ત વિસ્તાર પસંદ કરો',
    selectBodyPartDesc: 'લક્ષણોને ફિલ્ટર કરવા માટે શરીરનો મુખ્ય ભાગ પસંદ કરો.',
    selectSymptoms: 'લક્ષણો પસંદ કરો',
    selectSymptomsDesc: 'લક્ષણો પસંદ કરો અથવા તમારા પોતાના ટાઇપ કરો.',
    typeSymptomPlaceholder: 'અન્ય લક્ષણ ટાઇપ કરો...',
    severityDuration: 'તીવ્રતા અને સમયગાળો',
    selectSeverity: '૧. તીવ્રતાનું સ્તર પસંદ કરો',
    selectDuration: '૨. તમને કેટલા સમયથી લક્ષણો છે?',
    medicalHistory: 'તબીબી ઇતિહાસ',
    medicalHistoryDesc: 'ભલામણોને બહેતર બનાવવા માટે તમારા પહેલાના રોગો ઉમેરો.',
    existingConditions: 'પહેલાના રોગો',
    currentMedications: 'ચાલુ દવાઓ',
    allergies: 'એલર્જી',
    conditionsPlaceholder: 'દા.ત. ડાયાબિટીસ, હાઈ બ્લડ પ્રેશર',
    medicationsPlaceholder: 'દા.ત. ઇન્સ્યુલિન',
    allergiesPlaceholder: 'દા.ત. પેનિસિલિન',
    lifestyleFactors: 'જીવનશૈલીના પરિબળો',
    exerciseLevel: 'વ્યાયામનું સ્તર',
    stressLevel: 'તણાવનું સ્તર',
    dietType: 'આહારનો પ્રકાર',
    alcoholIntake: 'દારૂનું સેવન',
    smokingUse: 'તમાકુ / ધૂમ્રપાનનો ઉપયોગ',
    additionalContext: 'વધારાની માહિતી',
    additionalContextDesc: 'તાજેતરના ફેરફારો અથવા લક્ષણો શરૂ થવાની વિગતો સમજાવો.',
    contextPlaceholder: 'અહીં લખો...',
    analyzeBtn: 'લક્ષણોનું વિશ્લેષણ કરો',
    analysisResults: 'વિશ્લેષણ પરિણામો',
    potentialConditions: 'સંભવિત રોગો',
    lifestyleImpact: 'જીવનશૈલી પર અસર',
    remediesTitle: 'આયુર્વેદિક અને જીવનશૈલીના ઉપચારો',
    emergencySigns: '🚨 કટોકટીની ચેતવણીના ચિહ્નો (રેડ ફ્લેગ્સ)',
    newAnalysisBtn: 'નવું વિશ્લેષણ',
    geminiRunning: 'જેમિની AI દ્વારા લક્ષણોનું વિશ્લેષણ થઈ રહ્યું છે...',
    chatHeader: 'HealAI મદદગાર',
    chatPlaceholder: 'તમારા સ્વાસ્થ્ય વિશે પૂછો...',
    thinking: 'HealAI વિચારી રહ્યું છે...',
    clearChat: 'વાતચીત સાફ કરો',
    imageUploaded: 'છબી અપલોડ કરી',
    healthProfile: 'હેલ્થ પ્રોફાઇલ',
    healthProfileDesc: 'તમારી હેલ્થ પ્રોફાઇલ સેટ કરવા માટે ફેરફાર કરો પર ટેપ કરો',
    uploadReportBtn: 'મેડિકલ રિપોર્ટ અપલોડ કરો',
    uploadReportDesc: 'AI વિશ્લેષણ માટે લેબ રિપોર્ટ્સ, MRI, CT સ્કેન અથવા એક્સ-રે અપલોડ કરો',
    personalizedDiet: 'વ્યક્તિગત આહાર યોજના',
    generateDietBtn: 'તૈયાર કરો',
    regenerateDietBtn: 'ફરીથી તૈયાર કરો',
    dietPlaceholder: 'તમારી AI-આધારિત ભોજન યોજના બનાવવા માટે તૈયાર કરો પર ટેપ કરો',
    dailyAdviceTitle: 'દૈનિક સલાહ અને ઉપચારો',
    dailyAdvicePlaceholder: 'વ્યક્તિગત દૈનિક ભલામણો માટે તૈયાર કરો પર ટેપ કરો',
    naturalRemedies: '🌿 કુદરતી ઉપચારો',
    healthTools: 'આરોગ્ય સાધનો',
    educationHub: 'શિક્ષણ કેન્દ્ર',
    educationHubDesc: 'આરોગ્ય લેખો અને વિડિઓઝ',
    healthcareResources: 'આરોગ્ય સંસાધનો',
    healthcareResourcesDesc: 'તમારી નજીકની હોસ્પિટલો શોધો',
    emergencyCall: 'કટોકટી કૉલ',
    emergencyCallDesc: 'કટોકટી માટે 112 ડાયલ કરો',
    ambulanceCall: 'એમ્બ્યુલન્સ',
    ambulanceCallDesc: 'એમ્બ્યુલન્સ સેવાને કૉલ કરો',
    changeLanguage: 'ભાષા સેટિંગ્સ',
    changeLanguageDesc: 'એપ્લિકેશનની ભાષા બદલો',
    privacyPolicy: 'ગોપનીયતા નીતિ',
    privacyPolicyDesc: 'તમારો ડેટા સુરક્ષિત છે',
    aboutApp: 'HealAI વિશે',
    aboutAppDesc: 'આવૃત્તિ 1.0.0',
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    symptoms: 'ಲಕ್ಷಣಗಳು',
    chat: 'ಚಾಟ್',
    reports: 'ವರದಿಗಳು',
    more: 'ಇನ್ನಷ್ಟು',
    cancel: 'ರದ್ದುಮಾಡಿ',
    save: 'ಉಳಿಸಿ',
    edit: 'ಬದಲಾಯಿಸಿ',
    back: 'ಹಿಂದಕ್ಕೆ',
    next: 'ಮುಂದೆ',
    add: 'ಸೇರಿಸಿ',
    done: 'ಪೂರ್ಣ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    welcome: 'ನಿಮ್ಮ ಬುದ್ಧಿವಂತ ಆರೋಗ್ಯ ಸಂಗಾತಿ',
    subWelcome: 'ನಿಮ್ಮ ಬೆರಳ ತುದಿಯಲ್ಲಿ AI-ಮಾರ್ಗದರ್ಶಿತ ವೈದ್ಯಕೀಯ ಒಳನೋಟಗಳು ಮತ್ತು ವಿಶ್ಲೇಷಣೆಗಳು.',
    checkSymptomsBtn: 'ಲಕ್ಷಣಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    chatBotBtn: 'HealAI ಬಾಟ್ ಅನ್ನು ಕೇಳಿ',
    everythingYouNeed: 'ನಿಮಗೆ ಬೇಕಾಗಿರುವುದೆಲ್ಲವೂ',
    comprehensiveTools: 'ಉತ್ತಮ ಆರೋಗ್ಯಕ್ಕಾಗಿ ಸಮಗ್ರ ಉಪಕರಣಗಳು',
    symptomCheckerTitle: 'ಲಕ್ಷಣ ತಪಾಸಕ',
    symptomCheckerDesc: 'ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ ಮತ್ತು ತಕ್ಷಣದ ವೈದ್ಯಕೀಯ ಒಳನೋಟಗಳನ್ನು ಪಡೆಯಿರಿ.',
    healthChatbotTitle: 'ವೈದ್ಯಕೀಯ AI ಚಾಟ್‌ಬಾಟ್',
    healthChatbotDesc: 'ಯಾವುದೇ ಆರೋಗ್ಯ ಕಾಳಜಿಯ ಬಗ್ಗೆ ಜೆಮಿನಿ AI ಯೊಂದಿಗೆ ಸಮಾಲೋಚಿಸಿ ಅಥವಾ ವರದಿಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    healthReportsTitle: 'ಆರೋಗ್ಯ ದಾಖಲೆಗಳು',
    healthReportsDesc: 'ಸ್ಕ್ಯಾನ್/ಲ್ಯಾಬ್ ವರದಿಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ ಮತ್ತು ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
    nearbyHospitalsTitle: 'ಆರೋಗ್ಯ ಕೇಂದ್ರಗಳು',
    nearbyHospitalsDesc: 'ನಿಮ್ಮ ಹತ್ತಿರವಿರುವ ಪರಿಶೀಲಿಸಿದ ಆಸ್ಪತ್ರೆಗಳು ಮತ್ತು ಔಷಧಾಲಯಗಳನ್ನು ಹುಡುಕಿ.',
    howItWorks: 'ಮೂರು ಸರಳ ಹಂತಗಳು',
    step1Title: 'ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ',
    step1Desc: 'ನೈಸರ್ಗಿಕ ಭಾಷೆಯನ್ನು ಬಳಸಿಕೊಂಡು ನಮ್ಮ AI ಗೆ ನಿಮ್ಮ ಲಕ್ಷಣಗಳ ಬಗ್ಗೆ ತಿಳಿಸಿ.',
    step2Title: 'AI ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಿರಿ',
    step2Desc: 'ತತ್‌ಕ್ಷಣದ, ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಆರೋಗ್ಯ ಒಳನೋಟಗಳನ್ನು ಪಡೆಯಿರಿ.',
    step3Title: 'ಕ್ರಮ ಕೈಗೊಳ್ಳಿ',
    step3Desc: 'ನಿಮ್ಮ ಹತ್ತಿರದ ಆರೋಗ್ಯ ಪೂರೈಕೆದಾರರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ.',
    dailyInsight: 'ದೈನಂದಿನ ಆರೋಗ್ಯ ಒಳನೋಟ',
    healthDisclaimer: 'HealAI ಕೇವಲ ಶೈಕ್ಷಣಿಕ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಆರೋಗ್ಯ ಮಾಹಿತಿಯನ್ನು ಒದಗಿಸುತ್ತದೆ. ಇದು ವೃತ್ತಿಪರ ವೈದ್ಯಕೀಯ ಸಲಹೆಗೆ ಪರ್ಯಾಯವಲ್ಲ.',
    symptomCheckerHeader: 'ಲಕ್ಷಣ ತಪಾಸಕ',
    disclaimerWarning: 'ಇದು ಅಂತಿಮ ರೋಗನಿರ್ಣಯವಲ್ಲ. ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿ ತಕ್ಷಣ 112 ಗೆ ಕರೆ ಮಾಡಿ.',
    selectBodyPart: 'ಬಾಧಿತ ಪ್ರದೇಶವನ್ನು ಆರಿಸಿ',
    selectBodyPartDesc: 'ಲಕ್ಷಣಗಳನ್ನು ಫಿಲ್ಟರ್ ಮಾಡಲು ದೇಹದ ಪ್ರಾಥಮಿಕ ಭಾಗವನ್ನು ಆರಿಸಿ.',
    selectSymptoms: 'ಲಕ್ಷಣಗಳನ್ನು ಆರಿಸಿ',
    selectSymptomsDesc: 'ಲಕ್ಷಣಗಳನ್ನು ಆರಿಸಿ ಅಥವಾ ನಿಮ್ಮದೇ ಆದದನ್ನು ಟೈಪ್ ಮಾಡಿ.',
    typeSymptomPlaceholder: 'ಮತ್ತೊಂದು ಲಕ್ಷಣವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
    severityDuration: 'ತೀವ್ರತೆ ಮತ್ತು ಅವಧಿ',
    selectSeverity: '1. ತೀವ್ರತೆಯ ಮಟ್ಟವನ್ನು ಆರಿಸಿ',
    selectDuration: '2. ನಿಮಗೆ ಎಷ್ಟು ದಿನಗಳಿಂದ ಲಕ್ಷಣಗಳಿವೆ?',
    medicalHistory: 'ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ',
    medicalHistoryDesc: 'ಶಿಫಾರಸುಗಳನ್ನು ಉತ್ತಮಗೊಳಿಸಲು ನಿಮ್ಮ ಹಿಂದಿನ ಆರೋಗ್ಯ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಸೇರಿಸಿ.',
    existingConditions: 'ಹಿಂದಿನ ಆರೋಗ್ಯ ಪರಿಸ್ಥಿತಿಗಳು',
    currentMedications: 'ಪ್ರಸ್ತುತ ಔಷಧಿಗಳು',
    allergies: 'ಅಲರ್ಜಿಗಳು',
    conditionsPlaceholder: 'ಉದಾ: ಮಧುಮೇಹ, ಅಧಿಕ ರಕ್ತದೊತ್ತಡ',
    medicationsPlaceholder: 'ಉದಾ: ಇನ್ಸುಲಿನ್',
    allergiesPlaceholder: 'ಉದಾ: ಪೆನ್ಸಿಲಿನ್',
    lifestyleFactors: 'ಜೀವನಶೈಲಿ ಅಂಶಗಳು',
    exerciseLevel: 'ವ್ಯಾಯಾಮದ ಮಟ್ಟ',
    stressLevel: 'ಒತ್ತಡದ ಮಟ್ಟ',
    dietType: 'ಆಹಾರದ ಪ್ರಕಾರ',
    alcoholIntake: 'ಮದ್ಯಪಾನ ಸೇವನೆ',
    smokingUse: 'ತಂಬಾಕು / ಧೂಮಪಾನ ಬಳಕೆ',
    additionalContext: 'ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿ',
    additionalContextDesc: 'ಇತ್ತೀಚಿನ ಬದಲಾವಣೆಗಳು ಅಥವಾ ಲಕ್ಷಣಗಳ ಆರಂಭದ ವಿವರಗಳನ್ನು ವಿವರಿಸಿ.',
    contextPlaceholder: 'ಇಲ್ಲಿ ಬರೆಯಿರಿ...',
    analyzeBtn: 'ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
    analysisResults: 'ವಿಶ್ಲೇಷಣೆಯ ಫಲಿತಾಂಶಗಳು',
    potentialConditions: 'ಸಂಭಾವ್ಯ ಕಾಯಿಲೆಗಳು',
    lifestyleImpact: 'ಜೀವನಶೈಲಿಯ ಮೇಲಿನ ಪರಿಣಾಮ',
    remediesTitle: 'ಆಯುರ್ವೇದ ಮತ್ತು ಜೀವನಶೈಲಿ ಚಿಕಿತ್ಸೆಗಳು',
    emergencySigns: '🚨 ತುರ್ತು ಎಚ್ಚರಿಕೆ ಚಿಹ್ನೆಗಳು (ಕೆಂಪು ಎಚ್ಚರಿಕೆಗಳು)',
    newAnalysisBtn: 'ಹೊಸ ವಿಶ್ಲೇಷಣೆ',
    geminiRunning: 'ಜೆಮಿನಿ AI ಮೂಲಕ ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    chatHeader: 'HealAI ಸಹಾಯಕ',
    chatPlaceholder: 'ನಿಮ್ಮ ಆರೋಗ್ಯದ ಬಗ್ಗೆ ಕೇಳಿ...',
    thinking: 'HealAI ಯೋಚಿಸುತ್ತಿದೆ...',
    clearChat: 'ಸಂಭಾಷಣೆಯನ್ನು ಅಳಿಸಿ',
    imageUploaded: 'ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ',
    healthProfile: 'ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್',
    healthProfileDesc: 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಲು ಎಡಿಟ್ ಟ್ಯಾಪ್ ಮಾಡಿ',
    uploadReportBtn: 'ವೈದ್ಯಕೀಯ ವರದಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    uploadReportDesc: 'AI ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಲ್ಯಾಬ್ ವರದಿಗಳು, MRI, CT ಸ್ಕ್ಯಾನ್ ಅಥವಾ ಎಕ್ಸ್-ರೇಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    personalizedDiet: 'ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಆಹಾರ ಯೋಜನೆ',
    generateDietBtn: 'ರಚಿಸಿ',
    regenerateDietBtn: 'ಮತ್ತೆ ರಚಿಸಿ',
    dietPlaceholder: 'ನಿಮ್ಮ AI-ಚಾಲಿತ ಆಹಾರ ಯೋಜನೆಯನ್ನು ರಚಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    dailyAdviceTitle: 'ದೈನಂದಿನ ಸಲಹೆ ಮತ್ತು ಚಿಕಿತ್ಸೆಗಳು',
    dailyAdvicePlaceholder: 'ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ದೈನಂದಿನ ಶಿಫಾರಸುಗಳಿಗಾಗಿ ಟ್ಯಾಪ್ ಮಾಡಿ',
    naturalRemedies: '🌿 ನೈಸರ್ಗಿಕ ಚಿಕಿತ್ಸೆಗಳು',
    healthTools: 'ಆರೋಗ್ಯ ಉಪಕರಣಗಳು',
    educationHub: 'ಶಿಕ್ಷಣ ಕೇಂದ್ರ',
    educationHubDesc: 'ಆರೋಗ್ಯ ಲೇಖನಗಳು ಮತ್ತು ವೀಡಿಯೊಗಳು',
    healthcareResources: 'ಆರೋಗ್ಯ ಸಂಪನ್ಮೂಲಗಳು',
    healthcareResourcesDesc: 'ನಿಮ್ಮ ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗಳನ್ನು ಹುಡುಕಿ',
    emergencyCall: 'ತುರ್ತು ಕರೆ',
    emergencyCallDesc: 'ತುರ್ತು ಸಂದರ್ಭಗಳಿಗಾಗಿ 112 ಗೆ ಕರೆ ಮಾಡಿ',
    ambulanceCall: 'ಆಂಬ್ಯುಲೆನ್ಸ್',
    ambulanceCallDesc: 'ಆಂಬ್ಯುಲೆನ್ಸ್ ಸೇವೆಗೆ ಕರೆ ಮಾಡಿ',
    changeLanguage: 'ಭಾಷೆಯ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    changeLanguageDesc: 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಿ',
    privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    privacyPolicyDesc: 'ನಿಮ್ಮ ಡೇಟಾ ಸುರಕ್ಷಿತವಾಗಿದೆ',
    aboutApp: 'HealAI ಬಗ್ಗೆ',
    aboutAppDesc: 'ಆವೃತ್ತಿ 1.0.0',
  },
  or: {
    home: 'ହୋମ୍',
    symptoms: 'ଲକ୍ଷଣ',
    chat: 'ଚାଟ୍',
    reports: 'ରିପୋର୍ଟ',
    more: 'ଅଧିକ',
    cancel: 'ବାତିଲ୍',
    save: 'ସଂରକ୍ଷଣ',
    edit: 'ସଂଶୋଧନ',
    back: 'ପଛକୁ',
    next: 'ଆଗକୁ',
    add: 'ଯୋଡନ୍ତୁ',
    done: 'ସମାପ୍ତ',
    loading: 'ଲୋଡ୍ ହେଉଛି...',
    welcome: 'ଆପଣଙ୍କର ବୁଦ୍ଧିମାନ ସ୍ୱାସ୍ଥ୍ୟ ସାଥୀ',
    subWelcome: 'ଆପଣଙ୍କ ଆଙ୍ଗୁଠି ଅଗରେ AI-ନିର୍ଦ୍ଦେଶିତ ଚିକିତ୍ସା ସୂଚନା ଏବଂ ନିଦାନ ।',
    checkSymptomsBtn: 'ଲକ୍ଷଣ ଯାଞ୍ଚ କରନ୍ତୁ',
    chatBotBtn: 'HealAI ବୋଟ୍‌କୁ ପଚାରନ୍ତୁ',
    everythingYouNeed: 'ଆପଣଙ୍କର ସବୁ ଆବଶ୍ୟକତା',
    comprehensiveTools: 'ଉତ୍ਤମ ସ୍ୱାସ୍ଥ୍ୟ ପାଇଁ ବ୍ୟାପକ ସାଧନ',
    symptomCheckerTitle: 'ଲକ୍ଷଣ ଚେକର୍',
    symptomCheckerDesc: 'ଲକ୍ଷଣଗୁଡ଼ିକର ବିଶ୍ଳେଷଣ କରନ୍ତୁ ଏବଂ ତୁରନ୍ତ ଚିକିତ୍ସା ସୂଚନା ପାଆନ୍ତୁ ।',
    healthChatbotTitle: 'ମେଡିକାଲ୍ AI ଚାଟ୍‌ବୋଟ୍',
    healthChatbotDesc: 'ଯେକୌଣସି ସ୍ୱାସ୍ଥ୍ୟ ସମସ୍ୟା ବିଷୟରେ ଜେମିନି AI ସହିତ ପରାମର୍ଶ କରନ୍ତୁ କିମ୍ବା ରିପୋର୍ଟ ଅପ୍‌ଲୋଡ୍ କରନ୍ତୁ ।',
    healthReportsTitle: 'ସ୍ୱାସ୍ଥ୍ୟ ରେକର୍ଡ',
    healthReportsDesc: 'ସ୍କାନ୍/ଲ୍ୟାବ୍ ରିପୋର୍ଟଗୁଡିକର ବିଶ୍ଳେଷଣ କରନ୍ତୁ ଏବଂ ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରୋଫାଇଲ୍ ପରିଚାଳନା କରନ୍ତୁ ।',
    nearbyHospitalsTitle: 'ଚିକିତ୍ସାଳୟ ଖୋଜନ୍ତୁ',
    nearbyHospitalsDesc: 'ଆପଣଙ୍କ ନିକଟରେ ଥିବା ଯାଞ୍ਚ ହୋଇଥିବା ହସ୍ପିଟାଲ୍ ଏବଂ ଔଷଧ ଦୋକାନ ଖୋଜନ୍ତୁ ।',
    howItWorks: 'ତିନୋଟି ସରଳ ପଦକ୍ଷେପ',
    step1Title: 'ଲକ୍ଷଣର ବର୍ଣ୍ଣନା କରନ୍ତୁ',
    step1Desc: 'ପ୍ରାକୃତିକ ଭାଷା ବ୍ୟବਹାର କରି ଆମ AI କୁ ଆପଣଙ୍କ ଲକ୍ଷଣ ବିଷୟରେ କୁହନ୍ତୁ ।',
    step2Title: 'AI ବିଶ୍ଳେଷଣ ପାଆନ୍ତୁ',
    step2Desc: 'ତୁରନ୍ତ, ବ୍ୟକ୍ତିଗତ ସ୍ୱାସ୍ଥ୍ୟ ସୂଚନା ପାଆନ୍ତୁ ।',
    step3Title: 'ପଦକ୍ଷେପ ନିଅନ୍ତୁ',
    step3Desc: 'ଆପଣଙ୍କ ନିକଟରେ ଥିବା ସ୍ୱାସ୍ଥ୍ୟ ସେବା ପ୍ରଦାନକାରୀଙ୍କ ସହ ଯୋଡି ହୁଅନ୍ତୁ ।',
    dailyInsight: 'ଦୈନିକ ସ୍ୱାସ୍ଥ୍ୟ ସୂଚନା',
    healthDisclaimer: 'HealAI କେବଳ ଶିକ୍ଷାଗତ ଉଦ୍ଦେશ୍ୟରେ ସ୍ୱାସ୍ଥ୍ୟ ସୂଚନା ପ୍ରଦାନ କରେ । ଏହା ବୃତ୍ତିଗତ ଚିକਿତ୍ସା ପରାମର୍ଶର ବିକଳ୍ପ ନୁହେଁ ।',
    symptomCheckerHeader: 'ଲକ୍ଷଣ ଚେକର୍',
    disclaimerWarning: 'ଏହା ଚୂଡ଼ାନ୍ତ ନିଦାନ ନୁହେଁ। ଜରୁରୀକାଳୀନ ପରିସ୍ଥିତିରେ ତୁରନ୍ତ 112 କୁ କଲ୍ କରନ୍ତୁ ।',
    selectBodyPart: 'ପ୍ରଭାବିତ ଅଞ୍ચଳ ବାଛନ୍ତୁ',
    selectBodyPartDesc: 'ଲକ୍ଷଣଗୁଡ଼ିକୁ ଫିଲ୍ଟର୍ କରିବା ପାଇଁ ଶରୀରର ମୁଖ୍ୟ ଅଂଶ ବାଛନ୍ତୁ ।',
    selectSymptoms: 'ଲକ୍ଷଣ ବାଛନ୍ତୁ',
    selectSymptomsDesc: 'ଲକ୍ଷଣଗୁଡ଼ିକ ବାଛନ୍ତು କିମ୍ବା ନିଜେ ଟାଇପ୍ କରନ୍ତୁ ।',
    typeSymptomPlaceholder: 'ଅନ୍ୟ ଏକ ଲକ୍ଷଣ ଟାଇପ୍ କରନ୍ତୁ...',
    severityDuration: 'ତୀવ୍ରତା ଏବଂ ଅବଧି',
    selectSeverity: '୧. ତୀવ୍ରତା ସ୍ତର ବାଛନ୍ତୁ',
    selectDuration: '୨. ଆପଣଙ୍କର କେତେ ଦିନ ହେବ ଲକ୍ଷଣ ଦେଖାଯାଉଛି?',
    medicalHistory: 'ଚିକିତ୍ସା ଇତିହାସ',
    medicalHistoryDesc: 'ପରାମର୍ଶଗୁଡ଼ିକୁ ଉନ୍ନତ କରିବା ପାଇଁ ଆପଣଙ୍କର ପୂର୍ବ ରୋଗ ବିଷୟରେ ଯୋଡନ୍ତୁ ।',
    existingConditions: 'ପୂର୍ବରୁ ଥିବା ରୋଗ',
    currentMedications: 'ଚାଲୁଥିବା ଔଷଧ',
    allergies: 'ଆଲର୍ଜି',
    conditionsPlaceholder: 'ଯେପରିକି- ମଧୁମେਹ, ଉଚ୍ଚ ରକ୍ତଚାପ',
    medicationsPlaceholder: 'ଯେପରିକି- ଇନସୁଲିନ',
    allergiesPlaceholder: 'ଯେପରିକି- ପେନିସିଲିନ୍',
    lifestyleFactors: 'ଜୀવନଶୈଳୀ କାରକ',
    exerciseLevel: 'ବ୍ୟାୟାମ ସ୍ତର',
    stressLevel: 'ମାନସିକ ଚାପ ସ୍ତਰ',
    dietType: 'ଖାଦ୍ୟ ପ୍ରକାର',
    alcoholIntake: 'ମଦ୍ୟପାନ',
    smokingUse: 'ତମାଖୁ / ଧୂମପାନ ବ୍ୟବହାର',
    additionalContext: 'ଅଧିକ ବିବରଣୀ',
    additionalContextDesc: 'ନିକଟରେ ଘଟିଥିବା କୌଣସି ପରିବର୍ତ୍ତନ କିମ୍ବା ଆରମ୍ଭର ବିବରଣୀ ବୁଝାନ୍ତୁ ।',
    contextPlaceholder: 'ଏଠାରେ ଲେଖନ୍ତୁ...',
    analyzeBtn: 'ଲକ୍ଷଣର ବିଶ୍ଳେଷଣ କରନ୍ତು',
    analysisResults: 'ବିଶ୍ଳେଷଣର ଫଳାଫଳ',
    potentialConditions: 'ସମ୍ଭାବ୍ୟ ରୋଗଗୁଡିକ',
    lifestyleImpact: 'ଜୀવନଶୈଳୀ ଉପରେ ପ୍ରଭାବ',
    remediesTitle: 'ଆୟୁର୍ବେଦିକ ଏବଂ ଜୀବନଶୈଳୀ ପ୍ରତିକାର',
    emergencySigns: '🚨 ଜରୁରୀକାଳୀନ ଚେତାବନୀ ସଙ୍କେତ (ରେଡ୍ ଫ୍ଲାଗ୍)',
    newAnalysisBtn: 'ନୂତନ ବିଶ୍ଳେଷଣ',
    geminiRunning: 'ଜେମିନି AI ଦ୍ୱାରା ଲକ୍ଷଣ ବିଶ୍ଳେଷଣ କରାଯାଉଛି...',
    chatHeader: 'HealAI ସହାୟକ',
    chatPlaceholder: 'ଆପଣଙ୍କ ସ୍ୱାସ୍ଥ୍ୟ ବିଷୟରେ ପଚାରନ୍ତୁ...',
    thinking: 'HealAI ଚିନ୍ତା କରୁଛି...',
    clearChat: 'କଥାବାର୍ତ୍ତା ସଫା କରନ୍ତು',
    imageUploaded: 'ଛବି ଅପ୍‌ଲୋଡ୍ ହେଲା',
    healthProfile: 'ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରୋଫାଇଲ୍',
    healthProfileDesc: 'ସ୍ୱାସ୍ଥ୍ୟ ପ୍ରୋଫାଇଲ୍ ସେଟ୍ ଅପ୍ କରିବା ପାଇଁ ସଂଶୋଧନ ଉପରେ କ୍ଲିକ୍ କରନ୍ତು',
    uploadReportBtn: 'ଡାକ୍ତរୀ ରିପୋର୍ଟ ଅପ୍‌ଲୋଡ୍ କରନ୍ତು',
    uploadReportDesc: 'AI ବିଶ୍ଳେଷଣ ପାଇଁ ଲ୍ୟାବ୍ ରିପୋର୍ଟ, MRI, CT ସ୍କାନ୍ କିମ୍ବା ଏକ୍ସ-ରେ ଅପ୍‌ଲୋଡ୍ କରନ୍ତು',
    personalizedDiet: 'ବ୍ୟକ୍ତିଗତ ଖାଦ୍ୟ ଯୋଜନା',
    generateDietBtn: 'ପ୍ରସ୍ତուତ କରନ୍ତು',
    regenerateDietBtn: 'ପୁନଃ ପ୍ରସ୍ତուତ କରନ୍ତು',
    dietPlaceholder: 'ଆପଣଙ୍କର AI-ଚାଳିତ ଖାଦ୍ୟ ଯୋଜନା ପ୍ରସ୍ତուତ କରିବା ପାଇଁ କ୍ଲିକ୍ କରନ୍ତು',
    dailyAdviceTitle: 'ଦୈନିକ ପରାମର୍ଶ ଏବଂ ପ୍ରତିକାର',
    dailyAdvicePlaceholder: 'ବ୍ୟକ୍ତିਗତ ଦୈନିକ ପରାମର୍ଶ ପାଇଁ କ୍ଲିକ୍ କରନ୍ତು',
    naturalRemedies: '🌿 ପ୍ରାକୃତିକ ପ୍ରତିକାର',
    healthTools: 'ସ୍ୱାସ୍ଥ୍ୟ ସାଧନ',
    educationHub: 'ଶିକ୍ଷା କେନ୍ଦ୍ର',
    educationHubDesc: 'ସ୍ୱାସ୍ଥ୍ୟ ସମ୍ବନ୍ਧୀୟ ପ୍ରବନ୍ଧ ଏବଂ ଭିଡିଓ',
    healthcareResources: 'ସ୍ୱାସ୍ଥ୍ୟ ସମ୍ବଳ',
    healthcareResourcesDesc: 'ଆପଣଙ୍କ ନିକଟରେ ଥିବା ହସ୍ପିଟାଲ୍ ଖୋଜନ୍ତು',
    emergencyCall: 'ଜରୁରୀକାଳୀନ କଲ୍',
    emergencyCallDesc: 'ଜରୁਰୀକାଳୀନ ପରିସ୍ଥିତି ପାଇଁ 112 ଡାୟଲ୍ କରନ୍ତು',
    ambulanceCall: 'ଆମ୍ବୁଲାନ୍ସ',
    ambulanceCallDesc: 'ଆମ୍ବուଲାନ୍ସ ସେବାକୁ କଲ୍ କରନ୍ତು',
    changeLanguage: 'ଭାଷା ସେଟିଂସ',
    changeLanguageDesc: 'ଆପ୍ଲିକେସନ୍ ଭାଷା ପରିବର୍ତ୍તନ କରନ୍ତು',
    privacyPolicy: 'ଗୋପନୀୟତା ନୀତି',
    privacyPolicyDesc: 'ଆପଣଙ୍କ ତଥ୍ୟ ସୁରକ୍ଷିତ',
    aboutApp: 'HealAI ବିଷୟରେ',
    aboutAppDesc: 'ସଂସ୍କରଣ 1.0.0',
  },
  ml: {
    home: 'ഹോം',
    symptoms: 'ലക്ഷണങ്ങൾ',
    chat: 'ചാറ്റ്',
    reports: 'റിപ്പോർട്ടുകൾ',
    more: 'കൂടുതൽ',
    cancel: 'റദ്ദാക്കുക',
    save: 'സൂക്ഷിക്കുക',
    edit: 'തിരുത്തുക',
    back: 'പിന്നോട്ട്',
    next: 'അടുത്തത്',
    add: 'ചേർക്കുക',
    done: 'പൂർത്തിയായി',
    loading: 'ലോഡ് ചെയ്യുന്നു...',
    welcome: 'നിങ്ങളുടെ ബുദ്ധിമാനായ ആരോഗ്യ സഹായി',
    subWelcome: 'നിങ്ങളുടെ വിരൽത്തുമ്പിൽ എഐ-അധിഷ്ഠിത മെഡിക്കൽ വിവരങ്ങളും രോഗനിർണ്ണയവും.',
    checkSymptomsBtn: 'ലക്ഷണങ്ങൾ പരിശോധിക്കുക',
    chatBotBtn: 'HealAI ബോട്ടിനോട് ചോദിക്കുക',
    everythingYouNeed: 'നിങ്ങൾക്ക് ആവശ്യമുള്ളതെല്ലാം',
    comprehensiveTools: 'നല്ല ആരോഗ്യത്തിനായി സമഗ്രമായ ഉപകരണങ്ങൾ',
    symptomCheckerTitle: 'ലക്ഷണ പരിശോധകൻ',
    symptomCheckerDesc: 'ലക്ഷണങ്ങൾ വിശകലനം ചെയ്ത് ഉടനടി മെഡിക്കൽ വിവരങ്ങൾ നേടുക.',
    healthChatbotTitle: 'മെഡിക്കൽ എഐ ചാറ്റ്ബോട്ട്',
    healthChatbotDesc: 'ഏതെങ്കിലും ആരോഗ്യ പ്രശ്നത്തെക്കുറിച്ച് ജെമിനി എഐയുമായി കൂടിയാലോചിക്കുക അല്ലെങ്കിൽ റിപ്പോർട്ടുകൾ അപ്‌ലോഡ് ചെയ്യുക.',
    healthReportsTitle: 'ആരോഗ്യ രേഖകൾ',
    healthReportsDesc: 'സ്കാൻ/ലാബ് റിപ്പോർട്ടുകൾ വിശകലനം ചെയ്യുകയും ആരോഗ്യ പ്രൊഫൈലുകൾ കൈകാര്യം ചെയ്യുകയും ചെയ്യുക.',
    nearbyHospitalsTitle: 'ചികിത്സാലയങ്ങൾ കണ്ടെത്തുക',
    nearbyHospitalsDesc: 'നിങ്ങൾക്ക് സമീപമുള്ള പരിശോധിച്ചുറപ്പിച്ച ആശുപത്രികളും ഫാർമസികളും കണ്ടെത്തുക.',
    howItWorks: 'മൂന്ന് ലളിതമായ ഘട്ടങ്ങൾ',
    step1Title: 'ലക്ഷണങ്ങൾ വിവരിക്കുക',
    step1Desc: 'ലളിതമായ ഭാഷ ഉപയോഗിച്ച് ഞങ്ങളുടെ എഐയോട് നിങ്ങളുടെ ലക്ഷണങ്ങൾ പറയുക.',
    step2Title: 'എഐ വിശകലനം നേടുക',
    step2Desc: 'ഉടനടി വ്യക്തിഗതമാക്കിയ ആരോഗ്യ വിവരങ്ങൾ നേടുക.',
    step3Title: 'നടപടി സ്വീകരിക്കുക',
    step3Desc: 'നിങ്ങൾക്ക് സമീപമുള്ള ആരോഗ്യ സേവന ദാതാക്കളുമായി ബന്ധപ്പെടുക.',
    dailyInsight: 'ദൈനംദിന ആരോഗ്യ വിവരം',
    healthDisclaimer: 'HealAI വിദ്യാഭ്യാസ ആവശ്യങ്ങൾക്കായി മാത്രമുള്ള ആരോഗ്യ വിവരങ്ങൾ നൽകുന്നു. ഇത് പ്രൊഫഷണൽ മെഡിക്കல் ഉപദേശത്തിന് പകരമല്ല.',
    symptomCheckerHeader: 'ലക്ഷണ പരിശോധകൻ',
    disclaimerWarning: 'ഇത് രോഗനിർണ്ണയമല്ല. അടിയന്തിര സാഹചര്യങ്ങളിൽ ഉടൻ 112 ലേക്ക് വിളിക്കുക.',
    selectBodyPart: 'ബാധിച്ച ഭാഗം തിരഞ്ഞെടുക്കുക',
    selectBodyPartDesc: 'ലക്ഷണങ്ങൾ ഫിൽട്ടർ ചെയ്യുന്നതിനായി പ്രധാന ശരീര ഭാഗം തിരഞ്ഞെടുക്കുക.',
    selectSymptoms: 'ലക്ഷണങ്ങൾ തിരഞ്ഞെടുക്കുക',
    selectSymptomsDesc: 'ലക്ഷണങ്ങൾ തിരഞ്ഞെടുക്കുക അല്ലെങ്കിൽ സ്വന്തമായി ടൈപ്പ് ചെയ്യുക.',
    typeSymptomPlaceholder: 'മറ്റൊരു ലക്ഷണം ടൈപ്പ് ചെയ്യുക...',
    severityDuration: 'തീവ്രതയും കാലയളവും',
    selectSeverity: '1. തീവ്രതയുടെ നില തിരഞ്ഞെടുക്കുക',
    selectDuration: '2. നിങ്ങൾക്ക് എത്ര ദിവസമായി ലക്ഷണങ്ങളുണ്ട്?',
    medicalHistory: 'മെഡിക്കൽ ചരിത്രം',
    medicalHistoryDesc: 'നിർദ്ദേശങ്ങൾ മെച്ചപ്പെടുത്തുന്നതിനായി നിങ്ങളുടെ മുൻകാല ആരോഗ്യ വിവരങ്ങൾ ചേർക്കുക.',
    existingConditions: 'മുൻകാല രോഗങ്ങൾ',
    currentMedications: 'നിലവിലെ മരുന്നുകൾ',
    allergies: 'അലർജികൾ',
    conditionsPlaceholder: 'ഉദാ: പ്രമേഹം, ഉയർന്ന രക്തസമ്മർദ്ദം',
    medicationsPlaceholder: 'ഉദാ: ഇൻസുലിൻ',
    allergiesPlaceholder: 'ഉദാ: പെൻസിലിൻ',
    lifestyleFactors: 'ജീവിതശൈലി ഘടകങ്ങൾ',
    exerciseLevel: 'வ്യായാമത്തിന്റെ അളവ്',
    stressLevel: 'മാനസിക സമ്മർദ്ദത്തിന്റെ അളവ്',
    dietType: 'ഭക്ഷണ രീതി',
    alcoholIntake: 'മദ്യപാനം',
    smokingUse: 'പുകയില / പുകവലി ഉപയോഗം',
    additionalContext: 'അധിക വിവരങ്ങൾ',
    additionalContextDesc: 'സമീപകാലത്തുണ്ടായ മാറ്റങ്ങളോ ലക്ഷണങ്ങളുടെ തുടക്കമോ വിവരിക്കുക.',
    contextPlaceholder: 'ഇവിടെ എഴുതുക...',
    analyzeBtn: 'ലക്ഷണങ്ങൾ വിശകലനം ചെയ്യുക',
    analysisResults: 'വിശകലന ഫലങ്ങൾ',
    potentialConditions: 'സാധ്യതാ രോഗങ്ങൾ',
    lifestyleImpact: 'ജീവിതശൈലിയിലുള്ള സ്വാധീനം',
    remediesTitle: 'ആയുർവേദ & ജീവിതശൈലി പരിഹാരങ്ങൾ',
    emergencySigns: '🚨 അടിയന്തിര മുന്നറിയിപ്പ് ലക്ഷണങ്ങൾ (റെഡ് ഫ്ലാഗുകൾ)',
    newAnalysisBtn: '새로운 분석',
    geminiRunning: 'ജെമിനി എഐ വഴി ലക്ഷണങ്ങൾ വിശകലനം ചെയ്യുന്നു...',
    chatHeader: 'HealAI സഹായി',
    chatPlaceholder: 'ആരോഗ്യത്തെക്കുറിച്ച് ചോദിക്കൂ...',
    thinking: 'HealAI ചിന്തിക്കുന്നു...',
    clearChat: 'സംഭാഷണം ഇല്ലാതാക്കുക',
    imageUploaded: 'ചിത്രം അപ്‌ലോഡ് ചെയ്തു',
    healthProfile: 'ആരോഗ്യ പ്രൊഫൈൽ',
    healthProfileDesc: 'ആരോഗ്യ പ്രൊഫൈൽ സജ്ജീകരിക്കുന്നതിന് തിരുത്തുക എന്നത് അമർത്തുക',
    uploadReportBtn: 'മെഡിക്കൽ റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക',
    uploadReportDesc: 'എഐ വിശകലനത്തിനായി ലാബ് റിപ്പോർട്ടുകൾ, എംആർഐ, സിടി സ്കാൻ അല്ലെങ്കിൽ എക്സ്-റേകൾ അപ്‌ലോഡ് ചെയ്യുക',
    personalizedDiet: 'വ്യക്തിഗതമാക്കിയ ഭക്ഷണ ക്രമം',
    generateDietBtn: 'തയ്യാറാക്കുക',
    regenerateDietBtn: 'വീണ്ടും തയ്യാറാക്കുക',
    dietPlaceholder: 'നിങ്ങളുടെ എഐ-അധിഷ്ഠിത ഭക്ഷണക്രമം തയ്യാറാക്കാൻ അമർത്തുക',
    dailyAdviceTitle: 'ദൈനംദിന നിർദ്ദേശങ്ങളും പരിഹാരങ്ങളും',
    dailyAdvicePlaceholder: 'വ്യтельностиഗതമാക്കിയ ദൈനംദിന നിർദ്ദേശങ്ങൾക്കായി അമർത്തുക',
    naturalRemedies: '🌿 പ്രകൃതിദത്ത പരിഹാരങ്ങൾ',
    healthTools: 'ആരോഗ്യ ഉപകരണങ്ങൾ',
    educationHub: 'വിദ്യാഭ്യാസ കേന്ദ്രം',
    educationHubDesc: 'ആരോഗ്യ ലേഖനങ്ങളും വീഡിയോകളും',
    healthcareResources: 'ആരോഗ്യ വിഭവങ്ങൾ',
    healthcareResourcesDesc: 'നിങ്ങൾക്ക് സമീപമുള്ള ആശുപത്രികൾ കണ്ടെത്തുക',
    emergencyCall: 'അടിയന്തിര വിളി',
    emergencyCallDesc: 'അടിയന്തിര ആവശ്യങ്ങൾക്കായി 112 ലേക്ക് വിളിക്കുക',
    ambulanceCall: 'ആംബുലൻസ്',
    ambulanceCallDesc: 'ആംബുലൻസ് സേവനത്തിനായി വിളിക്കുക',
    changeLanguage: 'ഭാഷാ ക്രമീകരണങ്ങൾ',
    changeLanguageDesc: 'ആപ്ലിക്കേഷൻ ഭാഷ മാറ്റുക',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    privacyPolicyDesc: 'നിങ്ങളുടെ വിവരങ്ങൾ സുരക്ഷിതമാണ്',
    aboutApp: 'HealAI-യെ കുറിച്ച്',
    aboutAppDesc: 'പതിപ്പ് 1.0.0',
  },
  pa: {
    home: 'ਹੋਮ',
    symptoms: 'ਲੱਛਣ',
    chat: 'ਚੈਟ',
    reports: 'ਰਿਪੋਰਟਾਂ',
    more: 'ਹੋਰ',
    cancel: 'ਰੱਦ ਕਰੋ',
    save: 'ਸੁਰੱਖਿਅਤ ਕਰੋ',
    edit: 'ਸੋਧੋ',
    back: 'ਪਿੱਛੇ',
    next: 'ਅੱਗੇ',
    add: 'ਜੋੜੋ',
    done: 'ਪੂਰਾ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    welcome: 'ਤੁਹਾਡਾ ਸਿਆਣਾ ਸਿਹਤ ਸਾਥੀ',
    subWelcome: 'ਤੁਹਾਡੀ ਉਂਗਲਾਂ ਦੇ ਇਸ਼ਾਰੇ \'ਤੇ AI-ਨਿਰਦੇਸ਼ਿਤ ਡਾਕਟਰੀ ਸੂਝ ਅਤੇ ਨਿਦਾਨ।',
    checkSymptomsBtn: 'ਲੱਛਣਾਂ ਦੀ ਜਾਂਚ ਕਰੋ',
    chatBotBtn: 'HealAI ਬੋਟ ਨੂੰ ਪੁੱਛੋ',
    everythingYouNeed: 'ਉਹ ਸਭ ਕੁਝ ਜੋ ਤੁਹਾਨੂੰ ਚਾਹੀਦਾ ਹੈ',
    comprehensiveTools: 'ਬਿਹਤਰ ਸਿਹਤ ਲਈ ਵਿਆਪਕ ਸਾਧਨ',
    symptomCheckerTitle: 'ਲੱਛਣ ਚੈਕਰ',
    symptomCheckerDesc: 'ਲੱਛਣਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ ਅਤੇ ਤੁਰੰਤ ਡਾਕਟਰੀ ਸੂਝ ਪ੍ਰਾਪਤ ਕਰੋ।',
    healthChatbotTitle: 'ਮੈਡੀਕਲ AI ਚੈਟਬੋਟ',
    healthChatbotDesc: 'ਕਿਸੇ ਵੀ ਸਿਹਤ ਚਿੰਤਾ ਬਾਰੇ ਜੈਮਿਨੀ AI ਨਾਲ ਸਲਾਹ ਕਰੋ ਜਾਂ ਰਿਪੋਰਟਾਂ ਅਪਲੋਡ ਕਰੋ।',
    healthReportsTitle: 'ਸਿਹਤ ਰਿਕਾਰਡ',
    healthReportsDesc: 'ਸਕੈਨ/ਲੈਬ ਰਿਪੋਰਟਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ ਅਤੇ ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ।',
    nearbyHospitalsTitle: 'ਦੇਖਭਾਲ ਲੱਭੋ',
    nearbyHospitalsDesc: 'ਆਪਣੇ ਨੇੜੇ ਦੇ ਪ੍ਰਮਾਣਿਤ ਹਸਪਤਾਲ ਅਤੇ ਫਾਰਮੇਸੀਆਂ ਲੱਭੋ।',
    howItWorks: 'ਤਿੰਨ ਸਧਾਰਨ ਕਦਮ',
    step1Title: 'ਲੱਛਣਾਂ ਦਾ ਵਰਣਨ ਕਰੋ',
    step1Desc: 'ਕੁਦਰਤੀ ਭਾਸ਼ਾ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਸਾਡੇ AI ਨੂੰ ਆਪਣੇ ਲੱਛਣਾਂ ਬਾਰੇ ਦੱਸੋ।',
    step2Title: 'AI ਵਿਸ਼ਲੇਸ਼ਣ ਪ੍ਰਾਪત ਕਰੋ',
    step2Desc: 'ਤੁਰੰਤ, ਨਿੱਜੀ ਸਿਹਤ ਸੂਝ ਪ੍ਰਾਪਤ ਕਰੋ।',
    step3Title: 'ਕਾਰਵਾਈ ਕਰੋ',
    step3Desc: 'ਆਪਣੇ ਨੇੜੇ ਦੇ ਸਿਹਤ ਸੰਭਾਲ ਪ੍ਰਦਾਤਿਆਂ ਨਾਲ ਜੁੜੋ।',
    dailyInsight: 'ਰੋਜ਼ਾਨਾ ਸਿਹਤ ਸੂਝ',
    healthDisclaimer: 'HealAI ਸਿਰਫ ਵਿਦਿਅਕ ਉਦੇਸ਼ਾਂ ਲਈ ਸਿਹਤ ਜਾਣਕਾਰੀ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ। ਇਹ ਪੇਸ਼ੇਵਰ ਡਾਕਟਰੀ ਸਲਾਹ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ।',
    symptomCheckerHeader: 'ਲੱਛਣ ਚੈਕਰ',
    disclaimerWarning: 'ਇਹ ਕੋਈ ਅੰਤਿਮ ਨਿਦਾਨ ਨਹੀਂ ਹੈ। ਐਮਰਜੈਂਸੀ ਦੀ ਸਥਿਤੀ ਵਿੱਚ ਤੁਰੰਤ 112 ਡਾਇਲ ਕਰੋ।',
    selectBodyPart: 'ਪ੍ਰਭਾਵਿਤ ਖੇਤਰ ਚੁਣੋ',
    selectBodyPartDesc: 'ਲੱਛਣਾਂ ਨੂੰ ਫਿਲਟਰ ਕਰਨ ਲਈ ਸਰੀਰ ਦਾ ਮੁੱਖ ਹਿੱਸਾ ਚੁਣੋ।',
    selectSymptoms: 'ਲੱਛਣ ਚੁਣੋ',
    selectSymptomsDesc: 'ਲੱਛਣ ਚੁਣੋ ਜਾਂ ਆਪਣਾ ਖੁਦ ਟਾਈਪ ਕਰੋ।',
    typeSymptomPlaceholder: 'ਕੋਈ ਹੋਰ ਲੱਛਣ ਟਾਈਪ ਕਰੋ...',
    severityDuration: 'ਤੀਬਰਤਾ ਅਤੇ ਮਿਆਦ',
    selectSeverity: '1. ਤੀਬਰਤਾ ਦਾ ਪੱਧਰ ਚੁਣੋ',
    selectDuration: '2. ਤੁਹਾਨੂੰ ਕਦੋਂ ਤੋਂ ਲੱਛਣ ਮਹਿਸੂਸ ਹੋ ਰਹੇ ਹਨ?',
    medicalHistory: 'ਡਾਕਟਰੀ ਇਤਿਹਾਸ',
    medicalHistoryDesc: 'ਸਿਫਾਰਸ਼ਾਂ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਲਈ ਆਪਣੀਆਂ ਪਹਿਲਾਂ ਤੋਂ ਮੌਜੂਦ ਬਿਮਾਰੀਆਂ ਸ਼ਾਮਲ ਕਰੋ।',
    existingConditions: 'ਪਹਿਲਾਂ ਤੋਂ ਮੌਜੂਦ ਬਿਮਾਰੀਆਂ',
    currentMedications: 'ਮੌਜੂਦਾ ਦਵਾਈਆਂ',
    allergies: 'ਐਲਰਜੀ',
    conditionsPlaceholder: 'ਜਿਵੇਂ- ਸ਼ੂਗਰ, ਹਾਈ ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ',
    medicationsPlaceholder: 'ਜਿਵੇਂ- ਇਨਸੁਲਿਨ',
    allergiesPlaceholder: 'ਜਿਵੇਂ- ਪੈਨਸਿਲਿਨ',
    lifestyleFactors: 'ਜੀਵਨ ਸ਼ੈਲੀ ਦੇ ਕਾਰਕ',
    exerciseLevel: 'ਕਸਰਤ ਦਾ ਪੱਧਰ',
    stressLevel: 'ਤਣਾਅ ਦਾ ਪੱਧਰ',
    dietType: 'ਖੁਰਾਕ ਦੀ ਕਿਸਮ',
    alcoholIntake: 'ਸ਼ਰਾਬ ਦਾ ਸੇਵਨ',
    smokingUse: 'ਤੰਬਾਕੂ / ਸਿਗਰਟਨੋਸ਼ੀ ਦੀ ਵਰਤੋਂ',
    additionalContext: 'ਹੋਰ ਵੇਰਵੇ',
    additionalContextDesc: 'ਹਾਲ ਹੀ ਦੇ ਕਿਸੇ ਬਦਲਾਅ ਜਾਂ ਸ਼ੁਰੂਆਤ ਦੇ ਵੇਰਵਿਆਂ ਨੂੰ ਸਪਸ਼ਟ ਕਰੋ।',
    contextPlaceholder: 'ਇੱਥੇ ਲਿਖੋ...',
    analyzeBtn: 'ਲੱਛਣਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    analysisResults: 'ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜੇ',
    potentialConditions: 'ਸੰਭਾਵਿਤ ਬਿਮਾਰੀਆਂ',
    lifestyleImpact: 'ਜੀਵਨ ਸ਼ੈਲੀ \'ਤੇ ਪ੍ਰਭਾਵ',
    remediesTitle: 'ਆਯੁਰਵੇਦਿਕ ਅਤੇ ਜੀਵਨ ਸ਼ੈਲੀ ਦੇ ਉਪਚਾਰ',
    emergencySigns: '🚨 ਐਮਰਜੈਂਸੀ ਚੇਤਾਵਨੀ ਸੰਕੇਤ (ਰੈੱਡ ਫਲੈਗਸ)',
    newAnalysisBtn: 'ਨਵੀਂ ਜਾਂਚ',
    geminiRunning: 'ਜੈਮਿਨੀ AI ਦੁਆਰਾ ਲੱਛਣਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    chatHeader: 'HealAI ਸਹਾਇक',
    chatPlaceholder: 'ਆਪਣੀ ਸਿਹਤ ਬਾਰੇ ਪੁੱਛੋ...',
    thinking: 'HealAI ਸੋਚ ਰਿਹਾ ਹੈ...',
    clearChat: 'ਗੱਲਬਾਤ ਸਾਫ਼ ਕਰੋ',
    imageUploaded: 'ਤਸਵੀਰ ਅਪਲੋਡ ਕੀਤੀ ਗਈ',
    healthProfile: 'ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ',
    healthProfileDesc: 'ਆਪਣੀ ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ ਸੈੱਟ ਕਰਨ ਲਈ ਸੋਧੋ \'ਤੇ ਟੈਪ ਕਰੋ',
    uploadReportBtn: 'ਡਾਕਟਰੀ ਰਿਪੋਰਟ ਅਪਲੋਡ ਕਰੋ',
    uploadReportDesc: 'AI ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਲੈਬ ਰਿਪੋਰਟਾਂ, MRI, CT ਸਕੈਨ ਜਾਂ ਐਕਸ-ਰੇ ਅਪਲੋਡ ਕਰੋ',
    personalizedDiet: 'ਨਿੱਜੀ ਖੁਰਾਕ ਯੋਜਨਾ',
    generateDietBtn: 'ਤਿਆਰ ਕਰੋ',
    regenerateDietBtn: 'ਦੁਬਾਰਾ ਤਿਆਰ ਕਰੋ',
    dietPlaceholder: 'ਆਪਣੀ AI-ਸੰਚਾਲਿਤ ਖੁਰਾਕ ਯੋਜನಾ ਬਣਾਉਣ ਲਈ ਟੈਪ ਕਰੋ',
    dailyAdviceTitle: 'ਰੋਜ਼ਾਨਾ ਸਲਾਹ ਅਤੇ ਉਪਚਾਰ',
    dailyAdvicePlaceholder: 'ਨਿੱਜੀ ਰੋਜ਼ਾਨਾ ਸਿਫਾਰਸ਼ਾਂ ਲਈ ਟੈਪ ਕਰੋ',
    naturalRemedies: '🌿 ਕੁਦਰਤੀ ਉਪਚਾਰ',
    healthTools: 'ਸਿਹਤ ਸਾਧਨ',
    educationHub: 'ਸਿੱਖਿਆ ਕੇਂਦਰ',
    educationHubDesc: 'ਸਿਹਤ ਲੇਖ ਅਤੇ ਵੀਡੀਓ',
    healthcareResources: 'ਸਿਹਤ ਸੰਭਾਲ ਸਰੋਤ',
    healthcareResourcesDesc: 'ਆਪਣੇ ਨੇੜੇ ਦੇ ਹਸਪਤਾਲ ਲੱਭੋ',
    emergencyCall: 'ਐਮਰਜੈਂਸੀ ਕਾਲ',
    emergencyCallDesc: 'ਐਮਰਜੈਂਸੀ ਲਈ 112 ਡਾਇਲ ਕਰੋ',
    ambulanceCall: 'ਐਂਬੂਲੈਂਸ',
    ambulanceCallDesc: 'ਐਂਬੂਲੈਂਸ ਸੇਵਾ ਨੂੰ ਕਾਲ ਕਰੋ',
    changeLanguage: 'ਭਾਸ਼ਾ ਸੈਟਿੰਗਜ਼',
    changeLanguageDesc: 'ਐਪਲੀਕੇਸ਼ਨ ਦੀ ਭਾਸ਼ਾ ਬਦਲੋ',
    privacyPolicy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
    privacyPolicyDesc: 'ਤੁਹਾਡਾ ਡੇਟਾ ਸੁਰੱਖਿਅਤ ਹੈ',
    aboutApp: 'HealAI ਬਾਰੇ',
    aboutAppDesc: 'ਵਰਜਨ 1.0.0',
  },
};

async function translateDictionary(targetLanguage: string): Promise<Record<string, string>> {
  const prompt = `You are a professional medical translator. Translate the following English key-value dictionary into the ${targetLanguage} language.

English Dictionary:
${JSON.stringify(TRANSLATIONS.en, null, 2)}

CRITICAL REQUIREMENT: Return ONLY a valid JSON object matching the exact keys of the English dictionary. Do not change the keys. Translate only the values. Ensure medical terms are translated accurately and naturally in ${targetLanguage}. Do not write any conversational text or markdown code blocks around the JSON object. Just return raw JSON.`;

  const text = await callGemini(prompt, undefined, undefined, 'daily-insight');
  if (text) {
    const cleanedText = text
      .replace(/```json\n?|\n?```/g, '')
      .replace(/[\u201C\u201D]/g, '"')
      .replace(/\n\s*/g, ' ')
      .trim();
    return JSON.parse(cleanedText);
  }
  throw new Error('Empty response from model');
}

interface LanguageContextType {
  locale: LanguageCode;
  t: (key: string) => string;
  setLocale: (locale: LanguageCode) => Promise<void>;
}

const LanguageContext = createContext<LanguageContextType>({
  locale: 'en',
  t: (key: string) => key,
  setLocale: async () => { },
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<LanguageCode>('en');
  const [dynamicDictionary, setDynamicDictionary] = useState<Record<string, string>>({});

  useEffect(() => {
    const loadSavedLanguage = async () => {
      try {
        const saved = await AsyncStorage.getItem('appLanguage');
        if (saved && TRANSLATIONS[saved as LanguageCode]) {
          setLocaleState(saved as LanguageCode);
          
          const cacheKey = `cached_translation_${saved}`;
          const cached = await AsyncStorage.getItem(cacheKey);
          if (cached) {
            setDynamicDictionary(JSON.parse(cached));
          }
        }
      } catch (err) {
        console.error('Failed to load language', err);
      }
    };
    loadSavedLanguage();
  }, []);

  const triggerBackgroundTranslation = async (targetLocale: LanguageCode) => {
    try {
      const langName = SUPPORTED_LANGUAGES.find(l => l.code === targetLocale)?.name || targetLocale;
      const translated = await translateDictionary(langName);
      const cacheKey = `cached_translation_${targetLocale}`;
      await AsyncStorage.setItem(cacheKey, JSON.stringify(translated));
      
      setLocaleState(current => {
        if (current === targetLocale) {
          setDynamicDictionary(translated);
        }
        return current;
      });
    } catch (err) {
      console.warn('Background translation failed, relying on static dictionary', err);
    }
  };

  const setLocale = async (newLocale: LanguageCode) => {
    try {
      await AsyncStorage.setItem('appLanguage', newLocale);
      setLocaleState(newLocale);

      if (newLocale === 'en') {
        setDynamicDictionary({});
        return;
      }

      const cacheKey = `cached_translation_${newLocale}`;
      const cached = await AsyncStorage.getItem(cacheKey);
      if (cached) {
        setDynamicDictionary(JSON.parse(cached));
      } else {
        // Fetch in background to update cache silently without blocking UI
        triggerBackgroundTranslation(newLocale);
      }
    } catch (err) {
      console.error('Failed to save language', err);
    }
  };

  const t = (key: string): string => {
    if (dynamicDictionary && dynamicDictionary[key]) {
      return dynamicDictionary[key];
    }
    const dict = TRANSLATIONS[locale] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, t, setLocale }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);
